Mixky.desktop.Framework=function(a,b){function c(){h.setHeight(Ext.lib.Dom.getViewHeight()-i.el.getHeight())}function f(e){e.minimized=true;e.hide()}function d(e){j&&j!=e&&g(j);i.setActiveButton(e.taskButton);j=e;Ext.fly(e.taskButton.el).addClass("active-win");e.minimized=false}function g(e){if(e==j){j=null;Ext.fly(e.taskButton.el).removeClass("active-win")}}function l(e){i.taskButtonPanel.remove(e.taskButton);c()}Mixky.desktop.Framework.superclass.constructor.call(this,a,b);Ext.getBody().createChild({id:"x-desktop",
tag:"div"});Ext.getBody().createChild({id:"ux-taskbar",tag:"div",children:[{id:"ux-taskbar-start",tag:"div"},{id:"ux-taskbar-panel-wrap",tag:"div",children:[{id:"ux-quickstart-panel",tag:"div"},{id:"ux-taskbuttons-panel",tag:"div"}]},{id:"x-clear",tag:"div"}]});var k=new Ext.WindowGroup;this.getManager=function(){return k};this.getWindow=function(e){return k.get(e)};var j,h=Ext.get("x-desktop");this.el=h;var i=new Mixky.desktop.TaskBar(this);this.taskbar=i;this.shortcuts=new Mixky.desktop.Shortcuts({renderTo:h,
taskbarEl:i.el});this.contextmenu=new Ext.menu.Menu({items:[Mixky.app.Actions.Preferences,Mixky.app.Actions.SavePreferences,Mixky.app.Actions.DelPreferences,Mixky.app.Actions.SaveAsDefaultPreferences,"-",Mixky.app.Actions.ChangePassword,"-",Mixky.app.Actions.Help,Mixky.app.Actions.DesignTool,"-",Mixky.app.Actions.Exit,"-",Mixky.app.Actions.ShowDayTips,Mixky.app.Actions.About]});this.layout=c;Ext.EventManager.onWindowResize(c);this.getWinWidth=function(){var e=Ext.lib.Dom.getViewWidth();return e<200?
200:e};this.getWinHeight=function(){var e=Ext.lib.Dom.getViewHeight()-i.el.getHeight();return e<100?100:e};this.appendWindow=function(e){e.render(h);e.taskButton=i.taskButtonPanel.add(e);e.cmenu=new Ext.menu.Menu({items:[]});e.animateTarget=e.taskButton.el;e.on({activate:{fn:d},beforeshow:{fn:d},deactivate:{fn:g},minimize:{fn:f},close:{fn:l}});c();return e};this.createWindow=function(e,m){return this.appendWindow(new (m||Ext.Window)(Ext.applyIf(e||{},{manager:k,minimizable:true,maximizable:true})))};
h.on("contextmenu",function(e){if(e.target.id==h.id){e.stopEvent();this.contextmenu.el||this.contextmenu.render();e=e.getXY();e[1]-=this.contextmenu.el.getHeight();this.contextmenu.showAt(e)}},this);c()};
Ext.extend(Mixky.desktop.Framework,Mixky.desktop.IFramework,{init:function(){},getAnimateTarget:function(){return this.el},getStartConfig:function(){return{iconCls:"icon-sys-user",title:MixkyApp.USERNAME+"("+MixkyApp.USERDEPT+")"||"Mixky Desktop",toolItems:[Mixky.app.Actions.Preferences,Mixky.app.Actions.ChangePassword,"-",Mixky.app.Actions.Exit]}},setMenus:function(a){for(var b=0;b<a.length;b++)this.taskbar.startMenu.add({text:a[b].text,iconCls:a[b].iconCls,ignoreParentClicks:false,handler:MixkyApp.handlerMenu,
menu:this.getChildMenu(a[b])})},getChildMenu:function(a){var b;if(Ext.isDefined(a.items)){b=new Ext.menu.Menu({ignoreParentClicks:false});for(var c=0;c<a.items.length;c++)b.addMenuItem({text:a.items[c].text,name:a.items[c].name,iconCls:a.items[c].iconCls,handler:MixkyApp.handlerMenu,menu:this.getChildMenu(a.items[c])})}return b},setTheme:function(a){Ext.util.CSS.swapStyleSheet("theme",a)},setBackgroundColor:function(a){Ext.isIE?Ext.get(document.body).setStyle("background-color",a):Ext.get(document.body).setStyle("background-color",
"#"+a)},setFrontColor:function(a){Ext.isIE?Ext.util.CSS.updateRule(".ux-shortcut-btn-text","color",a):Ext.util.CSS.updateRule(".ux-shortcut-btn-text","color","#"+a)},setTransparency:function(a){this.taskbar.el.addClass("transparent");Ext.util.CSS.updateRule(".transparent","opacity",a/100);Ext.util.CSS.updateRule(".transparent","-moz-opacity",a/100);Ext.util.CSS.updateRule(".transparent","filter","alpha(opacity="+a+")")},setWallpaper:function(a){function b(){if(f.complete){d.cancel();c.setIconClass("x-icon-done");
c.setTitle("\u88c5\u8f7d\u5b8c\u6210");c.setMessage("\u5df2\u5b8c\u6210\u5899\u7eb8\u88c5\u8f7d.");MixkyApp.hideNotification(c);document.body.background=f.src}else d.delay(200)}var c=MixkyApp.showWaitMessage("\u6b63\u5728\u88c5\u8f7d\u5899\u7eb8..."),f=new Image;f.src=a;var d=new Ext.util.DelayedTask(b,this);d.delay(200)},setWallpaperPosition:function(a){if(a==="center"){a=Ext.get(document.body);a.removeClass("wallpaper-tile");a.addClass("wallpaper-center")}else if(a==="tile"){a=Ext.get(document.body);
a.removeClass("wallpaper-center");a.addClass("wallpaper-tile")}},addShortcut:function(a){a.handler=function(b,c){MixkyApp.executeAction(this.btntype,this.key,c)};this.shortcuts.addShortcut(a)},removeShortcut:function(a,b){(a=this.shortcuts.getButtonCmp(a,b))&&this.shortcuts.removeShortcut(a)},addQuickStart:function(a){a.handler=function(b,c){MixkyApp.executeAction(this.btntype,this.key,c)};a.tooltip=a.text;this.taskbar.quickStartPanel.add(a)},removeQuickStart:function(a,b){(a=this.taskbar.quickStartPanel.getButtonCmp(a,
b))&&this.taskbar.quickStartPanel.remove(a)},addSubject:function(a){var b=this,c=this.el.createChild({tag:"div",style:"position:absolute",id:"subject-div-"+a.key}),f=new Ext.Panel({id:"portlet-"+a.key,renderTo:c,width:a.width,height:a.height,title:a.text,floating:true,shadow:true,layout:"fit",x:a.left,y:a.top,style:{"z-index":1E3},iconCls:a.iconCls,tools:[{id:"refresh",handler:function(){f.doAutoLoad()},qtip:"\u91cd\u65b0\u88c5\u8f7d\u680f\u76ee\u5185\u5bb9"},{id:"gear",handler:function(){b.beginResizeSubject(f)},
qtip:"\u7f16\u8f91\u680f\u76ee\u4f4d\u7f6e"}],autoLoad:{url:"portlet.do",params:{key:a.key},scripts:true}});f.key=a.key},removeSubject:function(a){var b=Ext.getCmp("portlet-"+a);b&&b.destroy();(a=Ext.get("subject-div-"+a))&&a.remove()},showDesktop:function(){this.getManager().each(function(a){a.minimized=true;a.hide()})},getModule:function(a){a=this.getWindow("m-"+a);if(Ext.isDefined(a))return a.items.get(0)},getCurrentModule:function(){var a=this.getManager().getActive();if(a)if((a=a.items.get(0))&&
Ext.isDefined(a.getCurrentView))return a},openModule:function(a){var b=this.getWindow("m-"+a);if(!b){b=Mixky.app.Modules[a];if(!b)return;a=this.getModulePanel(a);b=this.createWindow({id:"m-"+b.key,title:b.title,iconCls:b.icon,layout:"fit",border:false,padding:2,width:this.getWinWidth()/1.1,height:this.getWinHeight()/1.1,items:a})}b.show();return b.items.get(0)},getDocument:function(a,b){a=this.getWindow("d-"+a.key+"-"+b);if(Ext.isDefined(a))return a.items.get(0)},_openDocument:function(a,b,c){var f=
this.getWindow("d-"+a.key+"-"+b);if(!Ext.isDefined(f)){c=this.getDocumentPanel(a.key,b,c);f=this.createWindow(Ext.apply({id:"d-"+a.key+"-"+b,title:a.title,iconCls:a.icon,layout:"fit",border:false,maximizable:false,width:500,height:500,items:c},a.config))}f.show();return f.items.get(0)},_closeDocument:function(a,b){a=this.getWindow("d-"+a+"-"+b);Ext.isDefined(a)&&a.close()},openWindow:function(a,b){var c=this.getWindow(a);c||this.createWindow(Ext.apply(b,{id:a}));return c},closeWindow:function(a){(a=
this.getWindow(a))&&a.close()},getResizer:function(){if(!this.resizerwrap){var a=this,b=this.el,c=b.createChild({tag:"div",style:"position:absolute;z-index : 15000"}),f=new Ext.Panel({renderTo:c,floating:true,hidden:true,dynamic:true,border:false,autoLoad:false,layout:"fit",tbar:["->",{text:"\u5b8c\u6210",iconCls:"icon-sys-cancel",handler:function(){a.stopResizeSubject()}}],draggable:{insertProxy:false,onDrag:function(){var d=this.proxy.getEl();this.x=d.getLeft(true);this.y=d.getTop(true);var g=this.panel.getEl().shadow;
g&&g.realign(this.x,this.y,d.getWidth(),d.getHeight())},endDrag:function(){this.panel.setPosition(this.x,this.y);if(this.panel.targetPanel){this.panel.targetPanel.setPosition(this.x,this.y);var d=MixkyApp.getSubject(this.panel.targetPanel.key);d.left=this.x;d.top=this.y}}},listeners:{resize:function(d){if(d.targetPanel){d.targetPanel.setSize(d.getSize());d.targetPanel.setPosition(d.getPosition(true));var g=MixkyApp.getSubject(d.targetPanel.key);g.width=d.getSize().width;g.height=d.getSize().height}}}});
f.dragPanel=new Ext.Resizable(f.getId(),{handles:"all",pinned:true,minWidth:50,minHeight:50,resizeRegion:b.getRegion(),listeners:{resize:function(d,g,l){f.setSize(g,l)}}});this.resizerwrap=f}return this.resizerwrap},stopResizeSubject:function(a){var b=this.getResizer();if(a&&b.targetPanel&&b.targetPanel.isVisible()){var c=MixkyApp.getSubject(b.targetPanel.key);c&&Ext.apply(c,a)}b.targetPanel=false;b.hide()},beginResizeSubject:function(a){var b=this.getResizer();b.dragPanel.resizeTo(a.getSize().width,
a.getSize().height);b.setPosition(a.getPosition());b.targetPanel=a;b.show();b.setSize(a.getSize().width,a.getSize().height);MixkyApp.getSubject(a.key)}});
Mixky.desktop.Shortcuts=function(a){function b(){l={index:1,x:g};k={index:1,y:g}}function c(h){if(h>Ext.lib.Dom.getViewHeight()-d.getHeight())return true;return false}var f=Ext.get(a.renderTo),d=a.taskbarEl,g=15,l=null,k=null,j=[];b();this.menu=new Ext.menu.Menu({items:[{iconCls:"icon-sys-open",text:"\u6253\u5f00",handler:function(h){h.parentMenu.button.handler()}},"-",{iconCls:"icon-sys-remove",text:"\u79fb\u9664",scope:this,handler:function(h){MixkyApp.removeShortcut(h.parentMenu.button.btntype,
h.parentMenu.button.key)}}]});this.addShortcut=function(h){var i=f.createChild({tag:"div",cls:"ux-shortcut-item"}),e=new Mixky.desktop.ShortcutButton(Ext.apply(h,{text:Ext.util.Format.ellipsis(h.text,25)}),i),m=this.menu;i.addListener("contextmenu",function(n){m.button=e;m.showAt(n.getXY())});j.push(e);this.setXY(e.container);return e};this.getButtonCmp=function(h,i){for(var e=0,m=j.length;e<m;e++)if(j[e].btntype==h&&j[e].key==i)return j[e]};this.removeShortcut=function(h){var i=document.getElementById(h.container.id);
h.destroy();i.parentNode.removeChild(i);i=[];for(var e=0,m=j.length;e<m;e++)j[e]!=h&&i.push(j[e]);j=i;this.handleUpdate()};this.handleUpdate=function(){b();for(var h=0,i=j.length;h<i;h++)this.setXY(j[h].container)};this.setXY=function(h){var i=k.y+74;if(c(k.y+74)&&i>74+g){l={index:l.index++,x:l.x+64+g};k={index:1,y:g}}h.setXY([l.x,k.y]);k.index++;k.y=k.y+74+g};Ext.EventManager.onWindowResize(this.handleUpdate,this,{delay:500})};
Mixky.desktop.ShortcutButton=function(a,b){Mixky.desktop.ShortcutButton.superclass.constructor.call(this,Ext.apply(a,{renderTo:b,template:new Ext.Template('<div class="ux-shortcut-btn '+a.iconCls+'">','<div style="background-color:transparent;" class="ux-shortcut-btn-img icon-sys-0shortcut'+a.btntype+"48 "+a.iconCls+'48"></div>','<div class="ux-shortcut-btn-text">{0}</div>',"</div>")}));this.btntype=a.btntype;this.key=a.key};
Ext.extend(Mixky.desktop.ShortcutButton,Ext.Button,{buttonSelector:"div:first",setButtonClass:function(){},setIconClass:function(a){this.el&&this.btnEl.replaceClass(this.iconCls,a);this.iconCls=a;return this},initButtonEl:function(a){Mixky.desktop.ShortcutButton.superclass.initButtonEl.apply(this,arguments);a.removeClass("x-btn");if(this.iconCls)this.cls||a.removeClass(this.text?"x-btn-text-icon":"x-btn-icon")},autoWidth:function(){},setText:function(a){this.text=a;this.el&&this.el.child("div.ux-shortcut-btn-text").update(a)}});
if(Ext.version.substr(0,2)!=="3."){Mixky.desktop.StartMenu=function(a){Mixky.desktop.StartMenu.superclass.constructor.call(this,a);a=this.toolItems;this.toolItems=new Ext.util.MixedCollection;a&&this.addTool.apply(this,a)};Ext.extend(Mixky.desktop.StartMenu,Ext.menu.Menu,{height:300,toolPanelWidth:100,width:300,ignoreParentClicks:true,render:function(){if(!this.el){var a=this.el=new Ext.Layer({cls:"x-menu ux-start-menu",shadow:this.shadow,constrain:false,parentEl:this.parentEl||document.body,zindex:15E3}),
b=a.createChild({tag:"div",cls:"x-window-header x-unselectable x-panel-icon "+this.iconCls});b.setStyle("padding","3px 0 0 0");this.header=b;b.createChild({tag:"span",cls:"x-window-header-text"});b.wrap({cls:"ux-start-menu-tl"});b.wrap({cls:"ux-start-menu-tr"});b.wrap({cls:"ux-start-menu-tc"});this.menuBWrap=a.createChild({tag:"div",cls:"ux-start-menu-body x-border-layout-ct ux-start-menu-body"});b=this.menuBWrap.wrap({cls:"ux-start-menu-ml"});this.menuBWrap.wrap({cls:"ux-start-menu-mc ux-start-menu-bwrap"});
this.menuPanel=this.menuBWrap.createChild({tag:"div",cls:"x-panel x-border-panel ux-start-menu-apps-panel opaque"});this.toolsPanel=this.menuBWrap.createChild({tag:"div",cls:"x-panel x-border-panel ux-start-menu-tools-panel"});b=b.wrap({cls:"x-window-bwrap"}).createChild({tag:"div",cls:"ux-start-menu-bc"});b.wrap({cls:"ux-start-menu-bl x-panel-nofooter"});b.wrap({cls:"ux-start-menu-br"});b.setStyle({height:"0px",padding:"0 0 6px 0"});this.keyNav=new Ext.menu.MenuNav(this);this.plain&&a.addClass("x-menu-plain");
this.cls&&a.addClass(this.cls);this.focusEl=a.createChild({tag:"a",cls:"x-menu-focus",href:"#",onclick:"return false;",tabIndex:"-1"});var c=this.menuPanel.createChild({tag:"ul",cls:"x-menu-list"}),f=this.toolsPanel.createChild({tag:"ul",cls:"x-menu-list"});a={click:{fn:this.onClick,scope:this},mouseover:{fn:this.onMouseOver,scope:this},mouseout:{fn:this.onMouseOut,scope:this}};c.on(a);Ext.isDefined(this.items)&&this.items.each(function(d){var g=document.createElement("li");g.className="x-menu-list-item";
c.dom.appendChild(g);d.render(g,this)},this);this.ul=c;this.autoWidth();f.on(a);this.toolItems.each(function(d){var g=document.createElement("li");g.className="x-menu-list-item";f.dom.appendChild(g);d.render(g,this)},this);this.toolsUl=f;this.autoWidth();this.menuBWrap.setStyle("position","relative");this.menuBWrap.setHeight(this.height);this.menuPanel.setStyle({padding:"2px",position:"absolute",overflow:"auto"});this.toolsPanel.setStyle({padding:"2px 4px 2px 2px",position:"absolute",overflow:"auto"});
this.setTitle(this.title)}},findTargetItem:function(a){if((a=a.getTarget(".x-menu-list-item",this.ul,true))&&a.menuItemId)return this.items.get(a.menuItemId)?this.items.get(a.menuItemId):this.toolItems.get(a.menuItemId)},show:function(a,b,c){this.parentMenu=c;this.el||this.render();this.fireEvent("beforeshow",this);this.showAt(this.el.getAlignToXY(a,b||this.defaultAlign),c,false);a=this.toolPanelWidth;b=this.menuBWrap.getBox();this.menuPanel.setWidth(b.width-a);this.menuPanel.setHeight(b.height);
this.toolsPanel.setWidth(a);this.toolsPanel.setX(b.x+b.width-a);this.toolsPanel.setHeight(b.height)},addTool:function(){for(var a=arguments,b=a.length,c,f=0;f<b;f++){var d=a[f];if(d.render)c=this.addToolItem(d);else if(typeof d=="string")c=d=="separator"||d=="-"?this.addToolSeparator():this.addText(d);else if(d.tagName||d.el)c=this.addElement(d);else if(typeof d=="object")c=this.addToolMenuItem(d)}return c},addToolSeparator:function(){return this.addToolItem(new Ext.menu.Separator({itemCls:"ux-toolmenu-sep"}))},
addToolItem:function(a){this.toolItems.add(a);if(this.toolsUl){var b=document.createElement("li");b.className="x-menu-list-item";this.toolsUl.dom.appendChild(b);a.render(b,this);this.delayAutoWidth()}return a},addToolMenuItem:function(a){a instanceof Ext.menu.Item||(a=typeof a.checked=="boolean"?new Ext.menu.CheckItem(a):new Ext.menu.Item(a));return this.addToolItem(a)},setTitle:function(a){this.title=a;this.header.child("span")&&this.header.child("span").update(a);return this},getToolButton:function(a){return new Ext.Button({handler:a.handler,
minWidth:this.toolPanelWidth-10,scope:a.scope,text:a.text})}})}else Mixky.desktop.StartMenu=Ext.extend(Ext.menu.Menu,{height:300,toolPanelWidth:100,width:300,ignoreParentClicks:true,initComponent:function(a){Mixky.desktop.StartMenu.superclass.initComponent.call(this,a);a=this.toolItems;this.toolItems=new Ext.util.MixedCollection;a&&this.addTool.apply(this,a)},onRender:function(a,b){Mixky.desktop.StartMenu.superclass.onRender.call(this,a,b);a=this.el.addClass("ux-start-menu");this.header=b=a.createChild({tag:"div",
cls:"x-window-header x-unselectable x-panel-icon "+this.iconCls});b.createChild({tag:"span",cls:"x-window-header-text"});b.wrap({cls:"ux-start-menu-tl"});b.wrap({cls:"ux-start-menu-tr"});b.wrap({cls:"ux-start-menu-tc"});this.menuBWrap=a.createChild({tag:"div",cls:"x-window-body x-border-layout-ct ux-start-menu-body"});a=this.menuBWrap.wrap({cls:"ux-start-menu-ml"});this.menuBWrap.wrap({cls:"x-window-mc ux-start-menu-bwrap"});this.menuPanel=this.menuBWrap.createChild({tag:"div",cls:"x-panel x-border-panel ux-start-menu-apps-panel"});
this.toolsPanel=this.menuBWrap.createChild({tag:"div",cls:"x-panel x-border-panel ux-start-menu-tools-panel"});a=a.wrap({cls:"x-window-bwrap"}).createChild({tag:"div",cls:"ux-start-menu-bc"});a.wrap({cls:"ux-start-menu-bl x-panel-nofooter"});a.wrap({cls:"ux-start-menu-br"});this.ul.appendTo(this.menuPanel);var c=this.toolsPanel.createChild({tag:"ul",cls:"x-menu-list"});this.mon(c,"click",this.onClick,this);this.mon(c,"mouseover",this.onMouseOver,this);this.mon(c,"mouseout",this.onMouseOut,this);Ext.isDefined(this.items)&&
this.items.each(function(f){f.parentMenu=this},this);this.toolItems.each(function(f){var d=document.createElement("li");d.className="x-menu-list-item";c.dom.appendChild(d);f.render(d);f.parentMenu=this},this);this.toolsUl=c;this.menuBWrap.setStyle("position","relative");this.menuBWrap.setHeight(this.height-28);this.menuPanel.setStyle({padding:"2px",position:"absolute",overflow:"auto"});this.toolsPanel.setStyle({padding:"2px 4px 2px 2px",position:"absolute",overflow:"auto"});this.setTitle(this.title)},
findTargetItem:function(a){if((a=a.getTarget(".x-menu-list-item",this.ul,true))&&a.menuItemId)return this.items.get(a.menuItemId)?this.items.get(a.menuItemId):this.toolItems.get(a.menuItemId)},show:function(a,b,c){this.parentMenu=c;this.el||this.render();this.fireEvent("beforeshow",this);this.showAt(this.el.getAlignToXY(a,b||this.defaultAlign),c,false);a=this.toolPanelWidth;b=this.menuBWrap.getBox();this.menuPanel.setWidth(b.width-a);this.menuPanel.setHeight(b.height);this.toolsPanel.setWidth(a);
this.toolsPanel.setX(b.x+b.width-a);this.toolsPanel.setHeight(b.height)},addTool:function(){for(var a=arguments,b=a.length,c,f=0;f<b;f++){var d=a[f];if(d.render)c=this.addToolItem(d);else if(typeof d=="string")c=d=="separator"||d=="-"?this.addToolSeparator():this.addText(d);else if(d.tagName||d.el)c=this.addElement(d);else if(typeof d=="object")c=this.addToolMenuItem(d)}return c},addToolSeparator:function(){return this.addToolItem(new Ext.menu.Separator({itemCls:"ux-toolmenu-sep"}))},addToolItem:function(a){this.toolItems.add(a);
if(this.toolsUl){var b=document.createElement("li");b.className="x-menu-list-item";this.toolsUl.dom.appendChild(b);a.render(b,this);this.delayAutoWidth()}return a},addToolMenuItem:function(a){a instanceof Ext.menu.Item||(a=typeof a.checked=="boolean"?new Ext.menu.CheckItem(a):new Ext.menu.Item(a));return this.addToolItem(a)},setTitle:function(a){this.title=a;this.header.child("span")&&this.header.child("span").update(a);return this},getToolButton:function(a){return new Ext.Button({handler:a.handler,
minWidth:this.toolPanelWidth-10,scope:a.scope,text:a.text})}});Mixky.desktop.TaskBar=function(a){this.desktop=a;this.init()};
Ext.extend(Mixky.desktop.TaskBar,Ext.util.Observable,{init:function(){this.startMenu=new Mixky.desktop.StartMenu(Ext.apply({iconCls:"icon-sys-user",title:"\u521b\u60f3\u5929\u7a7a\u529e\u516c\u7cfb\u7edf",height:300,width:250,shadow:true},this.desktop.getStartConfig()));this.startButton=Ext.version.substr(0,2)!=="3."?new Ext.Button({text:"\u5f00\u59cb",id:"ux-startbutton",iconCls:"start",menu:this.startMenu,menuAlign:"bl-tl",renderTo:"ux-taskbar-start"}):new Ext.Button({text:"\u5f00\u59cb",id:"ux-startbutton",
iconCls:"start",menu:this.startMenu,menuAlign:"bl-tl",renderTo:"ux-taskbar-start",clickEvent:"mousedown",template:new Ext.Template('<table border="0" cellpadding="0" cellspacing="0" class="x-btn-wrap x-btn {3}"><tbody><tr>','<td class="x-btn-left"><i>&#160;</i></td>','<td class="x-btn-center"><em class="{5}" unselectable="on">','<button class="x-btn-text {2}" type="{1}" style="height:30px;">{0}</button>',"</em></td>",'<td class="x-btn-right"><i>&#160;</i></td>',"</tr></tbody></table>")});var a=this.startButton.getEl().getWidth()+
10;a=new Ext.BoxComponent({el:"ux-taskbar-start",id:"TaskBarStart",minWidth:a,region:"west",split:false,width:a});this.quickStartPanel=new Mixky.desktop.QuickStartPanel({el:"ux-quickstart-panel",id:"TaskBarQuickStart",minWidth:60,region:"west",split:true,width:94});this.taskButtonPanel=new Mixky.desktop.TaskButtonsPanel({el:"ux-taskbuttons-panel",id:"TaskBarButtons",region:"center"});var b=new Ext.Container({el:"ux-taskbar-panel-wrap",items:[this.quickStartPanel,this.taskButtonPanel],layout:"border",
region:"center"});this.el=(new Mixky.desktop.TaskBarContainer({el:"ux-taskbar",layout:"border",items:[a,b]})).el;return this},setActiveButton:function(a){this.taskButtonPanel.setActiveButton(a)}});
Mixky.desktop.TaskBarContainer=Ext.extend(Ext.Container,{initComponent:function(){Mixky.desktop.TaskBarContainer.superclass.initComponent.call(this);this.el=Ext.get(this.el)||Ext.getBody();this.el.setHeight=Ext.emptyFn;this.el.setWidth=Ext.emptyFn;this.el.setSize=Ext.emptyFn;this.el.setStyle({overflow:"hidden",margin:"0",border:"0 none"});this.el.dom.scroll="no";this.allowDomMove=false;this.autoHeight=this.autoWidth=true;Ext.EventManager.onWindowResize(this.fireResize,this);this.renderTo=this.el},
fireResize:function(a,b){this.fireEvent("resize",this,a,b,a,b)}});
Mixky.desktop.TaskButtonsPanel=Ext.extend(Ext.BoxComponent,{activeButton:null,enableScroll:true,scrollIncrement:0,scrollRepeatInterval:400,scrollDuration:0.35,animScroll:true,resizeButtons:true,buttonWidth:168,minButtonWidth:118,buttonMargin:2,buttonWidthSet:false,initComponent:function(){Mixky.desktop.TaskButtonsPanel.superclass.initComponent.call(this);this.on("resize",this.delegateUpdates);this.items=[];this.stripWrap=Ext.get(this.el).createChild({cls:"ux-taskbuttons-strip-wrap",cn:{tag:"ul",cls:"ux-taskbuttons-strip"}});
this.stripSpacer=Ext.get(this.el).createChild({cls:"ux-taskbuttons-strip-spacer"});this.strip=new Ext.Element(this.stripWrap.dom.firstChild);this.edge=this.strip.createChild({tag:"li",cls:"ux-taskbuttons-edge"});this.strip.createChild({cls:"x-clear"})},add:function(a){var b=this.strip.createChild({tag:"li"},this.edge);a=new Mixky.desktop.TaskBar.TaskButton(a,b);this.items.push(a);if(!this.buttonWidthSet)this.lastButtonWidth=a.container.getWidth();this.setActiveButton(a);return a},remove:function(a){var b=
document.getElementById(a.container.id);a.destroy();b.parentNode.removeChild(b);b=[];for(var c=0,f=this.items.length;c<f;c++)this.items[c]!=a&&b.push(this.items[c]);this.items=b;this.delegateUpdates()},setActiveButton:function(a){this.activeButton=a;this.delegateUpdates()},delegateUpdates:function(){this.resizeButtons&&this.rendered&&this.autoSize();this.enableScroll&&this.rendered&&this.autoScroll()},autoSize:function(){var a=this.items.length,b=this.el.dom.clientWidth;if(!(!this.resizeButtons||
a<1||!b)){a=Math.max(Math.min(Math.floor((b-4)/a)-this.buttonMargin,this.buttonWidth),this.minButtonWidth);b=this.stripWrap.dom.getElementsByTagName("button");this.lastButtonWidth=Ext.get(b[0].id).findParent("li").offsetWidth;for(var c=0,f=b.length;c<f;c++){var d=b[c],g=Ext.get(b[c].id).findParent("li").offsetWidth;d.style.width=a-(g-d.offsetWidth)+"px"}}},autoScroll:function(){var a=this.items.length,b=this.el.dom.clientWidth,c=this.stripWrap,f=c.dom.offsetWidth,d=this.getScrollPos(),g=this.edge.getOffsetsTo(this.stripWrap)[0]+
d;if(!(!this.enableScroll||a<1||f<20)){c.setWidth(b);if(g<=b){c.dom.scrollLeft=0;if(this.scrolling){this.scrolling=false;this.el.removeClass("x-taskbuttons-scrolling");this.scrollLeft.hide();this.scrollRight.hide()}}else{this.scrolling||this.el.addClass("x-taskbuttons-scrolling");b-=c.getMargins("lr");c.setWidth(b>20?b:20);if(!this.scrolling)if(this.scrollLeft){this.scrollLeft.show();this.scrollRight.show()}else this.createScrollers();this.scrolling=true;if(d>g-b)c.dom.scrollLeft=g-b;else this.scrollToButton(this.activeButton,
true);this.updateScrollButtons()}}},createScrollers:function(){var a=this.el.dom.offsetHeight,b=this.el.insertFirst({cls:"ux-taskbuttons-scroller-left"});b.setHeight(a);b.addClassOnOver("ux-taskbuttons-scroller-left-over");this.leftRepeater=new Ext.util.ClickRepeater(b,{interval:this.scrollRepeatInterval,handler:this.onScrollLeft,scope:this});this.scrollLeft=b;b=this.el.insertFirst({cls:"ux-taskbuttons-scroller-right"});b.setHeight(a);b.addClassOnOver("ux-taskbuttons-scroller-right-over");this.rightRepeater=
new Ext.util.ClickRepeater(b,{interval:this.scrollRepeatInterval,handler:this.onScrollRight,scope:this});this.scrollRight=b},getScrollWidth:function(){return this.edge.getOffsetsTo(this.stripWrap)[0]+this.getScrollPos()},getScrollPos:function(){return parseInt(this.stripWrap.dom.scrollLeft,10)||0},getScrollArea:function(){return parseInt(this.stripWrap.dom.clientWidth,10)||0},getScrollAnim:function(){return{duration:this.scrollDuration,callback:this.updateScrollButtons,scope:this}},getScrollIncrement:function(){return this.scrollIncrement||
this.lastButtonWidth+2},scrollToButton:function(a,b){if(a=a.el.dom.parentNode){var c=a;a=this.getScrollPos();var f=this.getScrollArea(),d=Ext.fly(c).getOffsetsTo(this.stripWrap)[0]+a;c=d+c.offsetWidth;if(d<a)this.scrollTo(d,b);else c>a+f&&this.scrollTo(c-f,b)}},scrollTo:function(a,b){this.stripWrap.scrollTo("left",a,b?this.getScrollAnim():false);b||this.updateScrollButtons()},onScrollRight:function(){var a=this.getScrollWidth()-this.getScrollArea(),b=this.getScrollPos();a=Math.min(a,b+this.getScrollIncrement());
a!=b&&this.scrollTo(a,this.animScroll)},onScrollLeft:function(){var a=this.getScrollPos(),b=Math.max(0,a-this.getScrollIncrement());b!=a&&this.scrollTo(b,this.animScroll)},updateScrollButtons:function(){var a=this.getScrollPos();this.scrollLeft[a==0?"addClass":"removeClass"]("ux-taskbuttons-scroller-left-disabled");this.scrollRight[a>=this.getScrollWidth()-this.getScrollArea()?"addClass":"removeClass"]("ux-taskbuttons-scroller-right-disabled")}});
Mixky.desktop.TaskBar.TaskButton=Ext.version.substr(0,2)!=="3."?function(a,b){this.win=a;Mixky.desktop.TaskBar.TaskButton.superclass.constructor.call(this,{iconCls:a.iconCls,text:Ext.util.Format.ellipsis(a.title,12),tooltip:a.taskbuttonTooltip||a.title,renderTo:b,handler:function(){if(a.minimized||a.hidden)a.show();else a==a.manager.getActive()?a.minimize():a.toFront()},clickEvent:"mousedown"})}:function(a,b){this.win=a;Mixky.desktop.TaskBar.TaskButton.superclass.constructor.call(this,{iconCls:a.iconCls,
text:Ext.util.Format.ellipsis(a.title,12),tooltip:a.taskbuttonTooltip||a.title,renderTo:b,handler:function(){if(a.minimized||a.hidden)a.show();else a==a.manager.getActive()?a.minimize():a.toFront()},clickEvent:"mousedown",template:new Ext.Template('<table cellspacing="0" class="x-btn {3}"><tbody><tr>','<td class="x-btn-left"><i>&#160;</i></td>','<td class="x-btn-center"><em class="{5}" unselectable="on">','<button class="x-btn-text {2}" type="{1}" style="height:28px;">{0}</button>',"</em></td>",'<td class="x-btn-right"><i>&#160;</i></td>',
"</tr></tbody></table>")})};
Ext.extend(Mixky.desktop.TaskBar.TaskButton,Ext.Button,{onRender:function(){Mixky.desktop.TaskBar.TaskButton.superclass.onRender.apply(this,arguments);this.cmenu=new Ext.menu.Menu({items:[{id:Ext.version.substr(0,2)!=="3."?"restore":undefined,text:"\u8fd8\u539f",handler:function(){this.win.isVisible()?this.win.restore():this.win.show()},scope:this},{id:Ext.version.substr(0,2)!=="3."?"minimize":undefined,text:"\u6700\u5c0f\u5316",handler:this.win.minimize,scope:this.win},{id:Ext.version.substr(0,2)!==
"3."?"maximize":undefined,text:"\u6700\u5927\u5316",handler:this.win.maximize,scope:this.win},"-",{id:Ext.version.substr(0,2)!=="3."?"close":undefined,text:"\u5173\u95ed",handler:this.closeWin.createDelegate(this,this.win,true),scope:this.win}]});this.cmenu.on("beforeshow",function(){var a=this.cmenu.items.items,b=this.win;a[0].setDisabled(b.maximized!==true&&b.hidden!==true);a[1].setDisabled(b.minimized===true);a[2].setDisabled(b.maximized===true||b.hidden===true);a[2].setDisabled(b.maximizable===
false);a[3].setDisabled(b.closable===false)},this);this.el.on("contextmenu",function(a){a.stopEvent();this.cmenu.el||this.cmenu.render();a=a.getXY();a[1]-=this.cmenu.el.getHeight();this.cmenu.showAt(a)},this)},closeWin:function(a,b,c){c.isVisible()?c.restore():c.show();c.close()},setText:function(a){if(a){this.text=a;this.el&&this.el.child("td.x-btn-center "+this.buttonSelector).update(Ext.util.Format.ellipsis(a,12))}},setTooltip:function(a){if(a){this.tooltip=a;a=this.el.child(this.buttonSelector);
Ext.QuickTips.unregister(a.id);if(typeof this.tooltip=="object")Ext.QuickTips.register(Ext.apply({target:a.id},this.tooltip));else a.dom[this.tooltipType]=this.tooltip}}});
Mixky.desktop.QuickStartPanel=Ext.extend(Ext.BoxComponent,{enableMenu:true,initComponent:function(){Mixky.desktop.QuickStartPanel.superclass.initComponent.call(this);this.on("resize",this.delegateUpdates);this.menu=new Ext.menu.Menu;this.items=[];this.stripWrap=Ext.get(this.el).createChild({cls:"ux-quickstart-strip-wrap",cn:{tag:"ul",cls:"ux-quickstart-strip"}});this.stripSpacer=Ext.get(this.el).createChild({cls:"ux-quickstart-strip-spacer"});this.strip=new Ext.Element(this.stripWrap.dom.firstChild);
this.edge=this.strip.createChild({tag:"li",cls:"ux-quickstart-edge"});this.strip.createChild({cls:"x-clear"})},getButtonCmp:function(a,b){for(var c=0,f=this.items.length;c<f;c++)if(this.items[c].btntype==a&&this.items[c].key==b)return this.items[c]},add:function(a){var b=this.strip.createChild({tag:"li"},this.edge);b=Ext.version.substr(0,2)!=="3."?new Ext.Button(Ext.apply(a,{cls:"x-btn-icon",menuText:a.text,renderTo:b,text:""})):new Ext.Button(Ext.apply(a,{cls:"x-btn-icon",menuText:a.text,renderTo:b,
text:"",template:new Ext.Template('<table cellspacing="0" class="x-btn {3}"><tbody><tr>','<td class="x-btn-left"><i>&#160;</i></td>','<td class="x-btn-center"><em class="{5}" unselectable="on">','<button class="x-btn-text {2}" type="{1}">{0}</button>',"</em></td>",'<td class="x-btn-right"><i>&#160;</i></td>',"</tr></tbody></table>")}));b.btntype=a.btntype;b.key=a.key;this.items.push(b);this.delegateUpdates();return b},remove:function(a){var b=document.getElementById(a.container.id);a.destroy();b.parentNode.removeChild(b);
b=[];for(var c=0,f=this.items.length;c<f;c++)this.items[c]!=a&&b.push(this.items[c]);this.items=b;this.delegateUpdates()},menuAdd:function(a){this.menu.add(a)},delegateUpdates:function(){if(this.enableMenu&&this.rendered){this.showButtons();this.clearMenu();this.autoMenu()}},showButtons:function(){for(var a=this.items.length,b=0;b<a;b++)this.items[b].show()},clearMenu:function(){this.menu.removeAll()},autoMenu:function(){var a=this.items.length,b=this.el.dom.clientWidth,c=this.stripWrap,f=c.dom.offsetWidth,
d=this.edge.getOffsetsTo(this.stripWrap)[0];if(!(!this.enableMenu||a<1||f<20)){c.setWidth(b);if(d<=b){if(this.showingMenu){this.showingMenu=false;this.menuButton.hide()}}else{b-=c.getMargins("lr");c.setWidth(b>20?b:20);this.showingMenu||(this.menuButton?this.menuButton.show():this.createMenuButton());mo=this.getMenuButtonPos();for(a=a-1;a>=0;a--)if(this.items[a].el.dom.offsetLeft+this.items[a].el.dom.offsetWidth>mo){this.items[a].hide();b=this.items[a].initialConfig;this.menuAdd({iconCls:b.iconCls,
handler:b.handler,scope:b.scope,text:b.menuText})}else this.items[a].show();this.showingMenu=true}}},createMenuButton:function(){var a=this.el.dom.offsetHeight,b=this.el.insertFirst({cls:"ux-quickstart-menubutton-wrap"});b.setHeight(a);new Ext.Button({cls:"x-btn-icon",id:"ux-quickstart-menubutton",menu:this.menu,renderTo:b});b.setWidth(Ext.get("ux-quickstart-menubutton").getWidth());this.menuButton=b},getMenuButtonPos:function(){return this.menuButton.dom.offsetLeft}});