Ext.namespace("Mixky.editor");
Mixky.editor.DisplayField=Ext.extend(Ext.form.TextField,{defaultAutoCreate:{tag:"input",type:"hidden",name:this.name},htmlEncode:false,dictionaryname:undefined,remoterender:undefined,params:undefined,dourl:undefined,url:undefined,hideDisplayBorder:undefined,onRender:function(a,b){Mixky.editor.DisplayField.superclass.onRender.call(this,a,b);this.addEvents("aftersetvalue");this.wrap=this.el.wrap();this.displayEl=this.hideDisplayBorder?this.wrap.createChild({tag:"div",style:"padding:3px"}):this.wrap.createChild({tag:"div",
style:"border:1px solid #cccccc;padding:3px"});this.displayEl.dom.innerHTML="&nbsp;"},setValue:function(a){Mixky.editor.DisplayField.superclass.setValue.call(this,a);this.remoterender?this.renderValue(a):this.setRawValue(a);this.fireEvent("aftersetvalue",this);return this},setRawValue:function(a){var b=a;if(this.htmlEncode)b=Ext.util.Format.htmlEncode(a);if(b&&typeof b=="string")b=b.replaceAll("\n","<BR>").replaceAll("\t","&emsp;").replaceAll(" ","&nbsp;");this.displayEl.dom.innerHTML=Ext.isEmpty(b)?
"&nbsp;":b},renderValue:function(a){var b=a;if(Ext.isDefined(this.dictionaryname))b=Mixky.app.common.dictionaryRenderer(a,this.dictionaryname);else if(Ext.isDefined(this.dourl))Mixky.app.common.getDictionaryDourlRender(this.dourl,a,this.setRawValue.createDelegate(this),this.params);else Ext.isDefined(this.url)&&Mixky.app.common.getDictionaryUrlRender(this.url,a,this.setRawValue.createDelegate(this));this.setRawValue(b)}});Ext.reg("mixkydisplayfield",Mixky.editor.DisplayField);Ext.namespace("Mixky.editor");Ext.isDefined=function(a){return typeof a!=="undefined"};
Mixky.editor.PanelTriggerField=Ext.extend(Ext.form.TriggerField,{defaultAutoCreate:{tag:"input",type:"text",size:"24",autocomplete:"off"},listClass:"",listEmptyText:"",triggerClass:"x-form-arrow-trigger",shadow:"sides",listAlign:"tl-bl?",maxHeight:400,minHeight:120,resizable:false,handleHeight:8,minListWidth:120,lazyInit:true,confirm:true,valueFieldName:undefined,initComponent:function(){Mixky.editor.PanelTriggerField.superclass.initComponent.call(this);this.addEvents("expand","collapse","beforeselect",
"select","aftersetvalue");if(this.transform){var a=Ext.getDom(this.transform);if(!this.hiddenName)this.hiddenName=a.name;a.name=Ext.id();if(!this.lazyRender){this.target=true;this.el=Ext.DomHelper.insertBefore(a,this.autoCreate||this.defaultAutoCreate);this.render(this.el.parentNode,a)}Ext.removeNode(a)}},onRender:function(a,b){Mixky.editor.PanelTriggerField.superclass.onRender.call(this,a,b);if(this.hiddenName){this.hiddenField=this.el.insertSibling({tag:"input",type:"hidden",name:this.hiddenName,
id:this.hiddenId||this.hiddenName},"before",true);this.el.dom.removeAttribute("name")}Ext.isGecko&&this.el.dom.setAttribute("autocomplete","off");this.lazyInit?this.on("focus",this.initList,this,{single:true}):this.initList()},initList:function(){if(!this.list){this.list=new Ext.Layer({parentEl:this.getListParent(),shadow:this.shadow,cls:["x-panel",this.listClass].join(" "),constrain:false});var a=this.listWidth||Math.max(this.wrap.getWidth(),this.minListWidth);this.list.setSize(a,0);this.list.swallowEvent("mousewheel");
this.assetHeight=0;this.syncFont!==false&&this.list.setStyle("font-size",this.el.getStyle("font-size"));if(this.title){this.header=this.list.createChild({cls:"x-panel-hd",html:this.title});this.assetHeight+=this.header.getHeight()}this.innerList=this.list.createChild({cls:"x-panel-inner"});this.innerList.setWidth(a-this.list.getFrameWidth("lr"));this.panel=this.renderPanel(this.innerList);if(this.resizable){this.resizer=new Ext.Resizable(this.list,{pinned:true,handles:"se"});this.mon(this.resizer,
"resize",function(b,c,d){this.maxHeight=d-this.handleHeight-this.list.getFrameWidth("tb")-this.assetHeight;this.listWidth=c;this.innerList.setWidth(c-this.list.getFrameWidth("lr"));this.restrictHeight()},this);this.innerList.setStyle("margin-bottom",this.handleHeight+"px")}}},getListParent:function(){return document.body},initEvents:function(){Mixky.editor.PanelTriggerField.superclass.initEvents.call(this);this.keyNav=new Ext.KeyNav(this.el,{down:function(){this.onTriggerClick();this.delayedCheck=
true;this.unsetDelayCheck.defer(10,this)},esc:function(){this.collapse()},scope:this,doRelay:function(a,b,c){if(c=="down"||this.scope.isExpanded())return Ext.KeyNav.prototype.doRelay.apply(this,arguments);return true},forceKeyDown:true})},onDestroy:function(){Ext.destroy(this.resizer,this.panel,this.list);Mixky.editor.PanelTriggerField.superclass.onDestroy.call(this)},unsetDelayCheck:function(){delete this.delayedCheck},fireKey:function(a){var b=function(c){c.isNavKeyPress()&&!this.isExpanded()&&
!this.delayedCheck&&this.fireEvent("specialkey",this,c)};this.inEditor&&Ext.isWebKit&&a.getKey()==a.TAB?b.defer(10,this,[new Ext.EventObjectImpl(a)]):b.call(this,a)},onResize:function(a){Mixky.editor.PanelTriggerField.superclass.onResize.apply(this,arguments);if(this.list&&!Ext.isDefined(this.listWidth)){var b=Math.max(a,this.minListWidth);this.list.setWidth(b);this.innerList.setWidth(b-this.list.getFrameWidth("lr"))}},onEnable:function(){Mixky.editor.PanelTriggerField.superclass.onEnable.apply(this,
arguments);if(this.hiddenField)this.hiddenField.disabled=false},onDisable:function(){Mixky.editor.PanelTriggerField.superclass.onDisable.apply(this,arguments);if(this.hiddenField)this.hiddenField.disabled=true},getName:function(){var a=this.hiddenField;return a&&a.name?a.name:this.hiddenName||Mixky.editor.PanelTriggerField.superclass.getName.call(this)},initValue:function(){Mixky.editor.PanelTriggerField.superclass.initValue.call(this);if(this.hiddenField)this.hiddenField.value=Ext.isDefined(this.hiddenValue)?
this.hiddenValue:Ext.isDefined(this.value)?this.value:""},getValue:function(){return this.hiddenField?this.hiddenField.value:Mixky.editor.PanelTriggerField.superclass.getValue.call(this)},setValue:function(a){if(this.hiddenField)this.hiddenField.value=a;a=Mixky.editor.PanelTriggerField.superclass.setValue.call(this,a);this.fireEvent("aftersetvalue",this);return a},restrictHeight:function(){this.innerList.dom.style.height="";var a=this.innerList.dom,b=this.list.getFrameWidth("tb")+(this.resizable?
this.handleHeight:0)+this.assetHeight;a=Math.max(a.clientHeight,a.offsetHeight,a.scrollHeight);var c=this.getPosition()[1]-Ext.getBody().getScroll().top,d=Ext.lib.Dom.getViewHeight()-c-this.getSize().height;c=Math.max(c,d,this.minHeight||0)-this.list.shadowOffset-b-5;a=Math.min(a,c,this.maxHeight);this.innerList.setHeight(a);this.list.beginUpdate();this.list.setHeight(a+b);this.list.alignTo(this.wrap,this.listAlign);this.list.endUpdate()},onEmptyResults:function(){this.collapse()},isExpanded:function(){return this.list&&
this.list.isVisible()},validateBlur:function(){return!this.list||!this.list.isVisible()},collapse:function(){if(this.isExpanded()){this.list.hide();Ext.getDoc().un("mousewheel",this.collapseIf,this);Ext.getDoc().un("mousedown",this.collapseIf,this);this.fireEvent("collapse",this)}},collapseIf:function(a){!a.within(this.wrap)&&!a.within(this.list)&&this.panelCollapseIf(a)&&this.collapse()},panelCollapseIf:function(a){if(this.panel.collapseIf)return this.panel.collapseIf(a);return true},expand:function(){if(!(this.isExpanded()||
!this.hasFocus)){this.restrictHeight();this.list.alignTo(this.wrap,this.listAlign);Ext.isDefined(this.panel.beforeexpend)&&this.panel.beforeexpend(this,this.findValueFieldCmp());this.list.show();Ext.isGecko2&&this.innerList.setOverflow("auto");Ext.getDoc().on({scope:this,mousewheel:this.collapseIf,mousedown:this.collapseIf});this.panel.doLayout();this.fireEvent("expand",this)}},onTriggerClick:function(){if(!this.disabled){if(this.isExpanded())this.collapse();else{this.onFocus({});this.expand()}this.el.focus()}},
onSelect:function(a,b,c){if(this.fireEvent("beforeselect",this,a,b,c)!==false){if(Ext.isDefined(b)&&this.hiddenField){this.setValue(b,true);this.setRawValue(a)}else this.setValue(a);this.realValue=b;var d=this.findValueFieldCmp();Ext.isDefined(d)&&d.setValue(b);if(Ext.isDefined(c))this.recordsValue=c;this.collapse();this.fireEvent("select",this,a,b,c)}},findValueFieldCmp:function(){if(Ext.isDefined(this.valueFieldName)){var a=this.findParentByType("form");if(a)return a.getForm().findField(this.valueFieldName)}},
renderPanel:function(a){var b=[],c=new Ext.form.ComboBox({name:"testcombo",width:150,triggerAction:"all",mode:"local",editable:false,store:["test1","test2"]});if(this.confirm)b=["\u6d4b\u8bd5\u9009\u4e2d\u4e8b\u4ef6\uff1a",c,"->",{text:"\u786e\u5b9a",iconCls:"icon-designtool-confirm",handler:function(){this.onSelect("\u9009\u4e2d","selected")},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-designtool-cancel",handler:function(){this.collapse()},scope:this}];return new Ext.Panel({renderTo:a,layout:"fit",
items:[new Ext.Panel({autoScroll:true,bbar:b,html:"Mixky.editor.PanelTriggerField\uff1a\u4e0b\u62c9\u8f93\u5165\u57df<br><br>\u91cd\u8f7drenderPanel(el)\u65b9\u6cd5\u81ea\u5b9a\u4e49\u8f93\u5165\u754c\u9762\u3002<br><br>\u8303\u4f8b\uff1a<br><br>renderPanel : function(el){<br>\u3000\u3000var panel = new Ext.Panel({<br>\u3000\u3000\u3000\u3000applyTo: el,<br>\u3000\u3000\u3000\u3000html:'\u6d4b\u8bd5\u5f55\u5165\u7f16\u8f91\u7a97\u53e3'<br>\u3000\u3000});<br>\u3000\u3000return panel;<br>)"})],beforeexpend:function(){c.setValue("test2")},
collapseIf:function(d){if(c.wrap&&d.within(c.wrap))return false;if(c.list&&d.within(c.list))return false;return true}})}});Ext.reg("paneltriggerfield",Mixky.editor.PanelTriggerField);Ext.namespace("Mixky.editor");
Mixky.editor.ComboTree=Ext.extend(Mixky.editor.PanelTriggerField,{confirm:true,minListWidth:300,maxHeight:300,minHeight:200,resizable:false,selectMulti:true,valueAttribute:"key",displayAttribute:"text",valueSeparator:",",checkWithParent:true,valueFieldName:undefined,getRealValue:function(){var a=this.getValue(),b=this.findValueFieldCmp();if(b)a=b.getValue();return a},setRealValue:function(a){this.realValue=a;var b=this.findValueFieldCmp();b&&b.setValue(a);if(this.hiddenField)this.hiddenField.value=a},
findValueFieldCmp:function(){if(Ext.isDefined(this.valueFieldName)){var a=this.findParentByType("form");if(a)return a.getForm().findField(this.valueFieldName)}},onSelect:function(a,b,c){if(this.fireEvent("beforeselect",this,a,b,c)!==false){this.setValue(a);this.setRealValue(b);this.collapse();this.fireEvent("select",this,a,b,c)}},renderPanel:function(a){function b(f,e){e||(e=d.getRootNode());if(e.attributes[c.valueAttribute]==f)if(Ext.isDefined(e.attributes.checked)){e.attributes.checked=true;e.getUI().toggleCheck(true)}e.eachChild(function(g){b(f,
g)})}var c=this,d=new Ext.tree.TreePanel({region:"center",autoScroll:true,rootVisible:false,style:"background-color:white",root:{nodeType:"async",text:"\u6807\u7b7e\u9009\u62e9"},loader:new Ext.tree.TreeLoader({url:this.dataUrl||this.url,preloadChildren:true}),tools:[{id:"refresh",handler:function(){d.refresh()}}],refresh:function(){this.getRootNode().reload()}});d.getLoader().on("load",function(f,e){e.expand(true);if(Ext.isDefined(c.valueFieldName)){f=c.findParentByType("form").getForm().findField(c.valueFieldName);
Ext.isDefined(f.value)&&d.setValue(f.value)}else Ext.isDefined(c.value)&&d.setValue(c.value)});d.on("checkchange",function(f,e){if(e&&!c.selectMulti)for(var g=d.getChecked("id"),i=0;i<g.length;i++)g[i]!=f.id&&d.getNodeById(g[i]).getUI().toggleCheck(false);if(c.checkWithParent)e?d.checkAllParentNode(f.parentNode):d.unCheckAllChildNode(f)});d.checkAllParentNode=function(f){!f||f==this.getRootNode()||f.getUI().toggleCheck(true)};d.unCheckAllChildNode=function(f){f=f.childNodes;for(var e=0,g=f.length;e<
g;e++){if(!f[e]||f[e]==this.getRootNode())return;f[e].getUI().toggleCheck(false)}};d.setValue=function(f){if(c.selectMulti){f=f.split(c.valueSeparator);for(var e=0;e<f.length;e++)b(f[e])}else b(f)};var h=[];if(this.confirm)h=[{text:"\u5237\u65b0",iconCls:"icon-sys-refresh",handler:function(){d.refresh()}},"->",{text:"\u786e\u5b9a",iconCls:"icon-sys-confirm",handler:function(){var f=d.getChecked(this.valueAttribute),e=d.getChecked(this.displayAttribute),g="",i="";if(Ext.isDefined(f))for(var j=0;j<
f.length;j++)if(j==0){g=f[j];i=e[j]}else{g=g+this.valueSeparator+f[j];i=i+";"+e[j]}this.onSelect(i,g);this.collapse()},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-sys-cancel",handler:function(){this.collapse()},scope:this}];return new Ext.Panel({renderTo:a,layout:"fit",items:[new Ext.Panel({layout:"fit",height:300,items:[d],bbar:h})]})}});Ext.reg("combotree",Mixky.editor.ComboTree);Ext.namespace("Mixky.editor");
Mixky.editor.TextboxField=Ext.extend(Mixky.editor.PanelTriggerField,{confirm:true,editable:false,minListWidth:300,minHeight:200,getValue:function(){var a=this.value;if(a===this.emptyText||a===undefined)a="";return a},renderPanel:function(a){var b=new Ext.form.TextArea({hideLabel:true,anchor:"100%",height:200}),c=[];if(this.confirm)c=["->",{text:"\u786e\u5b9a",iconCls:"icon-designtool-confirm",handler:function(){var d=b.getValue();this.onSelect(d,d);this.collapse()},scope:this},"-",{text:"\u53d6\u6d88",
iconCls:"icon-designtool-cancel",handler:function(){this.collapse()},scope:this}];return new Ext.Panel({renderTo:a,layout:"fit",beforeexpend:function(d){b.setValue(d.value);b.value=d.value},items:[new Ext.Panel({layout:"fit",height:150,items:[b],bbar:c})]})}});Ext.reg("mixkytextboxfield",Mixky.editor.TextboxField);Ext.namespace("Mixky.editor");
Mixky.editor.CheckboxGroup=Ext.extend(Ext.form.CheckboxGroup,{defaultItems:[{boxLabel:"no options",disabled:true}],url:undefined,store:undefined,initComponent:function(){if(Ext.isDefined(this.url)&&this.url!=""){if(!Ext.isDefined(this.item))this.items=[];items=this.items;Ext.lib.Ajax.request("POST","page.do?url="+this.url,{success:function(a){for(var b=Ext.decode(a.responseText),c=0;c<b.length;c++){a=b[c];items.push({boxLabel:a.display,name:this.name+"_",inputValue:a.value})}},scope:this},null,{async:false})}Mixky.editor.CheckboxGroup.superclass.initComponent.call(this)},
onRender:function(a,b){if(!Ext.isDefined(this.items))this.items=[];if(this.items.length==0&&Ext.isDefined(this.store))for(var c=0;c<this.store.getCount();c++){var d=this.store.getAt(c);this.items.push({boxLabel:d.get("display"),name:this.name+"_",inputValue:d.get("value")})}if(this.items.length==0)this.items=this.defaultItems;Mixky.editor.CheckboxGroup.superclass.onRender.call(this,a,b)},getValue:function(){var a=[];this.eachItem(function(d){d.checked&&a.push(d)});for(var b="",c=0;c<a.length;c++)b=
c>0?b+","+a[c].inputValue:a[c].inputValue;return b},setValueForItem:function(a){a=String(a).split(",");for(var b=0;b<a.length;b++)this.eachItem(function(c){if(a[b]==c.inputValue){c.setValue(true);return false}})}});Ext.reg("mixkycheckboxgroup",Mixky.editor.CheckboxGroup);Ext.namespace("Mixky.editor");
Mixky.editor.RadioGroup=Ext.extend(Ext.form.RadioGroup,{defaultItems:[{boxLabel:"no options",disabled:true}],url:undefined,store:undefined,initComponent:function(){if(Ext.isDefined(this.url)&&this.url!=""){if(!Ext.isDefined(this.item))this.items=[];items=this.items;Ext.lib.Ajax.request("POST","page.do?url="+this.url,{success:function(a){for(var b=Ext.decode(a.responseText),c=0;c<b.length;c++){a=b[c];items.push({boxLabel:a.display,name:this.name+"_",inputValue:a.value})}},scope:this},null,{async:false})}Mixky.editor.RadioGroup.superclass.initComponent.call(this)},
onRender:function(a,b){if(!Ext.isDefined(this.items))this.items=[];if(this.items.length==0&&Ext.isDefined(this.store))for(var c=0;c<this.store.getCount();c++){var d=this.store.getAt(c);this.items.push({boxLabel:d.get("display"),name:this.name+"_",inputValue:d.get("value")})}if(this.items.length==0)this.items=this.defaultItems;Mixky.editor.RadioGroup.superclass.onRender.call(this,a,b)},getValue:function(){var a=Mixky.editor.RadioGroup.superclass.getValue.call(this),b="";if(a)b=a.inputValue;return b},
setValueForItem:function(a){this.eachItem(function(b){if(a==b.inputValue){b.setValue(true);return false}})}});Ext.reg("mixkyradiogroup",Mixky.editor.RadioGroup);Ext.namespace("Mixky.editor");
Mixky.editor.FileField=Ext.extend(Ext.form.DisplayField,{readOnly:false,isMulti:false,isImage:false,imageWidth:70,imageHeight:30,downloadUrl:"#",onRender:function(a,b){Mixky.editor.FileField.superclass.onRender.call(this,a,b);this.fileCount=0;this.fileInputs=[];if(!this.readOnly){this.btnInsertFileWrap=this.el.createChild({tag:"div",style:"position: absolute;"});this.btnInsertFile=new Ext.Button({renderTo:this.btnInsertFileWrap,text:"\u6dfb \u52a0 \u9644 \u4ef6",iconCls:"icon-sys-attachment"});this.addFileInput()}},
bindFileField:function(a){a.on({scope:this,mouseenter:function(){this.btnInsertFile.addClass(["x-btn-over","x-btn-focus"])},mouseleave:function(){this.btnInsertFile.removeClass(["x-btn-over","x-btn-focus","x-btn-click"])},mousedown:function(){this.btnInsertFile.addClass("x-btn-click")},mouseup:function(){this.btnInsertFile.removeClass(["x-btn-over","x-btn-focus","x-btn-click"])},change:function(){this.addFileDisplay(0,this.curFileInput.dom.value,0,this.curFileInput)}})},getFileRowHeight:function(){return this.isImage?
this.imageHeight+2:22},adjustFileInputTop:function(){var a=this.fileCount*this.getFileRowHeight()+2;if(!this.readOnly&&(this.isMulti||this.fileCount==1)){var b=(this.fileCount-1)*this.getFileRowHeight();this.btnInsertFileWrap.setTop(b);this.curFileInput.setTop(b)}if(!this.readOnly&&!this.isMulti)if(this.fileCount>1){this.btnInsertFileWrap.hide();this.curFileInput.setDisplayed("none");this.curFileInput.hide();a=this.getFileRowHeight()+2}else{this.btnInsertFileWrap.show();this.curFileInput.setDisplayed("");
this.curFileInput.show()}if(this.readOnly){this.curFileInput.setDisplayed("none");this.curFileInput.hide()}this.setHeight(a)},addFileInput:function(){this.curFileInput=this.el.createChild({name:this.name+"-0-"+this.fileCount,style:"position: absolute;-moz-opacity: 0;filter:alpha(opacity: 0);opacity: 0;z-index: 2; height: 22px;",tag:"input",type:"file",size:1});var a=this.findParentByType("form");Ext.isDefined(a)&&a.doLayout();this.bindFileField(this.curFileInput);this.fileCount++;this.adjustFileInputTop();
this.fileInputs.push(this.curFileInput)},addFileDisplay:function(a,b,c,d){c=b+(c>0?" ("+c+"Bytes)":"");var h=this.el.createChild({tag:"div",style:"height: "+this.getFileRowHeight()+"px;"});if(a>0){b=this.downloadUrl!="#"?this.downloadUrl+"&id="+a+"&filename="+b:"#";if(this.isImage)c="<img align=middle border=0 height="+this.imageHeight+" width="+this.imageWidth+' src="'+b+"\" title='"+c+"'>";b=h.createChild({tag:"a",href:b,html:c});if(!this.readOnly){h.insertHtml("beforeEnd","\u3000");b=h.createChild({tag:"a",
href:"#",html:"\u5220\u9664"});b.on("click",function(){h.remove();this.fileCount--;this.adjustFileInputTop();this.fileInputs.push(this.el.createChild({name:this.name+"-"+a,style:"display:none",tag:"input",type:"file"}))},this)}this.fileCount++;this.fileInputs.push(h);this.adjustFileInputTop()}else{b=h.createChild({tag:"a",href:"#",html:b});if(!this.readOnly){h.insertHtml("beforeEnd","\u3000");b=h.createChild({tag:"a",href:"#",html:"\u5220\u9664"});b.on("click",function(){d.remove();h.remove();this.fileCount--;
this.adjustFileInputTop()},this)}this.fileInputs.push(h);d.setDisplayed("none");this.addFileInput();this.isMulti||this.curFileInput.setDisplayed("none")}},setValue:function(a){for(var b=0;b<this.fileInputs.length;b++)this.fileInputs[b].remove();this.fileInputs=[];this.fileCount=0;this.addFileInput();if(a instanceof Array)for(b=0;b<a.length;b++)this.addFileDisplay(a[b].id,a[b].filename,a[b].filesize)}});Ext.reg("mixkyfilefield",Mixky.editor.FileField);Ext.namespace("Mixky.editor");
Mixky.editor.OrganizationWindowField=Ext.extend(Ext.form.TriggerField,{defaultAutoCreate:{tag:"textarea",name:this.name},htmlEncode:false,editable:false,selectOnFocus:false,blankText:"\u5168\u90e8",selectMulti:true,selectType:"mix",valueField:"expression",displayField:"f_caption",valueSeparator:";",valueFieldName:undefined,onTriggerClick:function(){var a={selectMulti:this.selectMulti,selectType:this.selectType,valueField:this.valueField,displayField:this.displayField,valueSeparator:this.valueSeparator};
value="";var b=this,c=this.findValueFieldCmp();if(c)value=c.getValue();Mixky.app.common.getOrganizationWindow(a,value,function(d,h){b.setValue(d);c&&c.setValue(h)}).show()},findValueFieldCmp:function(){if(Ext.isDefined(this.valueFieldName)){var a=this.findParentByType("form");if(a)return a.getForm().findField(this.valueFieldName)}}});Ext.reg("mixkyorganizationwindowfield",Mixky.editor.OrganizationWindowField);Ext.namespace("Mixky.editor");
Mixky.editor.OpinionField=Ext.extend(Ext.form.TextField,{hideDisplayBorder:undefined,defaultAutoCreate:{tag:"input",type:"hidden",name:this.name},onRender:function(a,b){Mixky.editor.OpinionField.superclass.onRender.call(this,a,b);this.wrap=this.el.wrap();this.opinionEl=this.wrap.createChild({tag:"div"});this.hideDisplayBorder||this.wrap.setStyle("border","1px solid #cccccc");this.opinionEl.setStyle("padding","3px");if(!this.readOnly){a=this.wrap.createChild({tag:"div",align:"right"}).createChild({tag:"div"});
(new Ext.SplitButton({iconCls:"icon-sys-btnedit",text:"\u586b\u5199\u610f\u89c1",handler:this.openOpinionWindow,menu:new Ext.menu.Menu({items:[{text:"\u540c\u610f",handler:function(){this.setDirectOpinion("\u540c\u610f")},scope:this},{text:"\u5df2\u9605",handler:function(){this.setDirectOpinion("\u5df2\u9605")},scope:this},{text:"\u4e0d\u540c\u610f",handler:function(){this.setDirectOpinion("\u4e0d\u540c\u610f")},scope:this}]}),scope:this})).render(a)}this.loadValue()},loadValue:function(){FlowAppDirect.getDisplayOpinion(this.document.document.documentkey,
this.document.document.documentid,this.name,function(a,b){a&&a.success?this.setOpinion(a.opinion):MixkyApp.showDirectActionFail("\u83b7\u53d6\u610f\u89c1",a,b)},this)},openOpinionWindow:function(){Mixky.workflow.OpinionWindow(this.document.document.documentkey,this.document.document.documentid,{objectkey:this.name,objectid:this.id})},setDirectOpinion:function(a){FlowAppDirect.setOpinion(this.document.document.documentkey,this.document.document.documentid,a,this.name,function(b){b&&b.success&&this.loadValue()},
this)},initValue:function(){this.value!==""?this.setOpinion(this.value):this.setOpinion("&nbsp;")},setOpinion:function(a){if(a!="&nbsp;")this.value=a;if(this.opinionEl)this.opinionEl.dom.innerHTML=a===""||a===null||a===undefined?"&nbsp;":a},getValue:function(){if(!this.rendered)return this.value;var a=this.opinionEl.dom.innerHTML;if(a===this.emptyText||a===undefined)a="";return a},validate:function(){return true}});Ext.reg("mixkyopinionfield",Mixky.editor.OpinionField);Ext.namespace("Mixky.editor");
Mixky.editor.SignField=Ext.extend(Ext.form.TextField,{nextAction:1,defaultAutoCreate:{tag:"input",type:"hidden",name:this.name},onRender:function(a,b){Ext.form.TextField.superclass.onRender.call(this,a,b);this.wrap=this.el.wrap();this.wrap.setStyle("padding","2px");this.opinionEl=this.wrap.createChild({tag:"div",style:"float:left"});if(!this.readOnly){this.opinionButtonEl=this.wrap.createChild({tag:"div",align:"right"});this.opinionButton=new Ext.Button({text:"\u7b7e\u540d",handler:this.sign,scope:this});
this.opinionButton.render(this.opinionButtonEl)}},loadValue:function(a){DocumentAppDirect.getUserSignDisplay(a,function(b){b&&b.success&&this.setSign(b.sign)},this)},sign:function(){var a=this.getValue();!Ext.isDefined(a)||a==null||a==""?this.setValue(Mixky.app.UserInfo.name):this.setValue()},setSign:function(a){if(a!="&nbsp;")this.value=a;if(this.opinionEl)this.opinionEl.dom.innerHTML=a===""||a===null||a===undefined?"&nbsp;":a},setValue:function(a){Ext.form.TextField.superclass.setValue.call(this,
a);if(Ext.isDefined(a)&&a!=null&&a!=""){this.loadValue(a);this.opinionButton&&this.opinionButton.setText("\u53d6\u6d88")}else{this.setSign(a);this.opinionButton&&this.opinionButton.setText("\u7b7e\u540d")}}});Ext.reg("mixkysignfield",Mixky.editor.SignField);Ext.ns("Mixky.app.favorite");Mixky.app.favorite.FavoriteColumn=function(a){Ext.apply(this,a);if(!this.id)this.id=Ext.id();this.renderer=this.renderer.createDelegate(this)};
Mixky.app.favorite.FavoriteColumn.prototype={init:function(a){this.grid=a;this.grid.on("render",function(){this.grid.getView().mainBody.on("mousedown",this.onMouseDown,this)},this)},onMouseDown:function(a,b){if(b.className&&b.className.indexOf("x-grid3-cc-"+this.id)!=-1){a.stopEvent();a=this.grid.getView().findRowIndex(b);var c=this.grid.getStore().getAt(a),d=0;if(c.data[this.dataIndex]==0)d=1;a=c.data[this.titleFieldName];b=this.documenttypekey;var h=c.get("ID");if(this.documenttypekey=="mkFavorite.dtFavorite"){b=
c.get("F_SOURCE_KEY");h=c.get("F_SOURCE_PARAM")}var f=this;Mixky.app.common.updateFavorite(b,h,a,d,function(){c.set(f.dataIndex,d);c.commit()})}},renderer:function(a,b){b.css+=" x-grid3-check-col-td";return'<div class="x-grid3-check-col'+(a>0?"-on":"")+" x-grid3-cc-"+this.id+" mixky-favorite-"+(a>0?"on":"off")+'">&#160;</div>'}};Ext.namespace("Mixky.editor");
Mixky.editor.ComboViewField=Ext.extend(Mixky.editor.PanelTriggerField,{editable:false,minListWidth:400,maxHeight:500,minHeight:200,resizable:false,remoterenderer:true,viewkey:"",groupkey:"",renderPanel:function(a){Ext.lib.Ajax.request("POST","page.do?url=framework/engine/view/combo.view&viewkey="+this.viewkey,{success:function(d){eval(d.responseText)},scope:this},null,{async:false});var b=this.viewpanel,c=new Ext.tree.TreePanel({region:"west",width:150,minSize:100,maxSize:300,split:true,collapsible:true,
collapseMode:"mini",rootVisible:false,autoScroll:true,animCollapse:false,iconCls:"icon-sys-modulemenu",title:"\u68c0\u7d22\u5bfc\u822a",tools:[{id:"refresh",handler:function(){c.refresh()}}],listeners:{afterrender:function(d){d.getRootNode().expand()}},root:{id:"root",text:"root",type:"groupitem",params:{groupkey:this.groupkey}},loader:new Ext.tree.TreeLoader({directFn:ModuleAppDirect.getModuleTree,paramOrder:["params"],baseParams:{params:{}},listeners:{beforeload:function(d,h){d.baseParams.params=
c.getNodeParams(h);d.baseParams.params.type=h.attributes.type}}}),selModel:new Ext.tree.DefaultSelectionModel({listeners:{selectionchange:function(d,h){c.openNode(h)}}}),getNodeParams:function(d){var h={};d.parentNode&&Ext.apply(h,this.getNodeParams(d.parentNode));Ext.apply(h,d.attributes.params);return h},refresh:function(d){d||(d=this.getSelectionModel().getSelectedNode());!d||d.isLeaf()||d.reload()},openNode:function(d){d||(d=this.getSelectionModel().getSelectedNode());if(d)if(!d.attributes.isFunctionMenu){d=
this.getNodeParams(d);b.refresh(d)}}});this.onSelectRecord=function(){var d=b.getKey();this.onSelect(b.getDisplay(),d);this.collapse()};return new Ext.Panel({renderTo:a,layout:"border",border:false,bbar:["->",{text:"\u786e\u5b9a",iconCls:"icon-sys-confirm",handler:function(){this.onSelectRecord()},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-sys-cancel",handler:function(){this.collapse()},scope:this}],height:300,items:[c,b]})},setValue:function(a,b){!Ext.isDefined(this.valueFieldName)&&b!==
true&&Ext.isDefined(a)&&a!=""&&a!=0&&this.renderValue(a);return Mixky.editor.ComboViewField.superclass.setValue.call(this,a)},renderValue:function(a){this.remoterenderer&&Mixky.app.common.getDictionaryDourlRender("framework/engine/view/combo.view.renderer",a,this.setRawValue.createDelegate(this),{viewkey:this.viewkey})}});Ext.reg("mixkycomboviewfield",Mixky.editor.ComboViewField);Ext.namespace("Mixky.editor");
Mixky.editor.EmailAddress=Ext.extend(Ext.form.TextArea,{queryDelay:500,queryParam:"query",minChars:1,minListWidth:200,lazyInit:true,listClass:"",displayField:"display",selectedClass:"x-combo-selected",shadow:"sides",listAlign:"tl-bl?",maxHeight:300,minHeight:90,itemSeparator:",",url:"emailaddress.jsp",directFn:undefined,initComponent:function(){Mixky.editor.EmailAddress.superclass.initComponent.call(this);this.addEvents("expand","collapse","beforeselect","select","beforequery");var a=new Ext.data.JsonReader({root:"results",
totalProperty:"rows",fields:[this.displayField]});this.store=Ext.isDefined(this.directFn)?new Ext.data.Store({proxy:new Ext.data.DirectProxy({directFn:this.directFn,paramsAsHash:true,paramOrder:[this.queryParam]}),reader:a}):new Ext.data.Store({proxy:new Ext.data.HttpProxy({url:this.url}),reader:a});if(!Ext.isDefined(this.initialConfig.minChars))this.minChars=0;this.selectedIndex=-1},initEvents:function(){Mixky.editor.EmailAddress.superclass.initEvents.call(this);this.keyNav=new Ext.KeyNav(this.el,
{up:function(){this.inKeyMode=true;this.selectPrev()},down:function(){this.inKeyMode=true;this.selectNext()},enter:function(){this.onViewClick();this.delayedCheck=true;this.unsetDelayCheck.defer(10,this)},esc:function(){this.collapse()},tab:function(){this.onViewClick(false);return true},scope:this,doRelay:function(a,b,c){if(c=="down"||this.scope.isExpanded())return Ext.KeyNav.prototype.doRelay.apply(this,arguments);return true},forceKeyDown:true});this.queryDelay=Math.max(this.queryDelay||250);this.dqTask=
new Ext.util.DelayedTask(this.initQuery,this);this.editable!==false&&!this.enableKeyEvents&&this.mon(this.el,"keyup",this.onKeyUp,this)},onRender:function(a,b){Mixky.editor.EmailAddress.superclass.onRender.call(this,a,b);this.wrap=this.el.wrap({cls:"x-form-field-wrap x-form-field-trigger-wrap"});this.width||this.wrap.setWidth(this.el.getWidth());Ext.isGecko&&this.el.dom.setAttribute("autocomplete","off");this.lazyInit?this.on("focus",this.initList,this,{single:true}):this.initList()},initList:function(){if(!this.list){this.list=
new Ext.Layer({parentEl:this.getListParent(),shadow:this.shadow,cls:["x-combo-list",this.listClass].join(" "),constrain:false});var a=this.listWidth||Math.max(this.wrap.getWidth(),this.minListWidth);this.list.setSize(a,0);this.list.swallowEvent("mousewheel");this.assetHeight=0;this.syncFont!==false&&this.list.setStyle("font-size",this.wrap.getStyle("font-size"));if(this.title){this.header=this.list.createChild({cls:"x-combo-list-hd",html:this.title});this.assetHeight+=this.header.getHeight()}this.innerList=
this.list.createChild({cls:"x-combo-list-inner"});this.mon(this.innerList,"mouseover",this.onViewOver,this);this.mon(this.innerList,"mousemove",this.onViewMove,this);this.innerList.setWidth(a-this.list.getFrameWidth("lr"));if(!this.tpl)this.tpl='<tpl for="."><div class="x-combo-list-item">{'+this.displayField+"}</div></tpl>";this.view=new Ext.DataView({applyTo:this.innerList,tpl:this.tpl,singleSelect:true,selectedClass:this.selectedClass,itemSelector:this.itemSelector||".x-combo-list-item",emptyText:this.listEmptyText});
this.mon(this.view,"click",this.onViewClick,this);this.bindStore(this.store,true)}},getStore:function(){return this.store},getListParent:function(){return document.body},onKeyUp:function(a){var b=a.getKey();if(this.editable!==false&&(b==a.BACKSPACE||!a.isSpecialKey())){this.lastKey=b;this.dqTask.delay(this.queryDelay)}Mixky.editor.EmailAddress.superclass.onKeyUp.call(this,a)},bindStore:function(a,b){if(this.store&&!b){this.store.un("beforeload",this.onBeforeLoad,this);this.store.un("load",this.onLoad,
this);this.store.un("exception",this.collapse,this);this.store!==a&&this.store.autoDestroy&&this.store.destroy();if(!a){this.store=null;this.view&&this.view.bindStore(null)}}if(a){this.store=Ext.StoreMgr.lookup(a);this.store.on({scope:this,beforeload:this.onBeforeLoad,load:this.onLoad,exception:this.collapse});this.view&&this.view.bindStore(a)}},onBeforeLoad:function(){if(this.hasFocus){this.innerList.update(this.loadingText?'<div class="loading-indicator">'+this.loadingText+"</div>":"");this.restrictHeight();
this.selectedIndex=-1}},onLoad:function(){if(this.hasFocus)if(this.store.getCount()>0){this.expand();this.restrictHeight();this.select(0,true)}else this.onEmptyResults()},onEmptyResults:function(){this.collapse()},validateBlur:function(){return!this.list||!this.list.isVisible()},initQuery:function(){var a=this.getItemText();a==""||Ext.isEmpty(a)?this.collapse():this.doQuery(this.getItemText())},doQuery:function(a){a=Ext.isEmpty(a)?"":a;a={query:a,field:this,cancel:false};if(this.fireEvent("beforequery",
a)===false||a.cancel)return false;a=a.query;this.store.baseParams[this.queryParam]=a;this.store.load();this.expand()},unsetDelayCheck:function(){delete this.delayedCheck},isExpanded:function(){return this.list&&this.list.isVisible()},select:function(a,b){this.selectedIndex=a;this.view.select(a);if(b!==false)(a=this.view.getNode(a))&&this.innerList.scrollChildIntoView(a,false)},selectPrev:function(){if(this.store.getCount()>0)if(this.selectedIndex==-1)this.select(0);else this.selectedIndex!==0&&this.select(this.selectedIndex-
1)},selectNext:function(){var a=this.store.getCount();if(a>0)if(this.selectedIndex==-1)this.select(0);else this.selectedIndex<a-1&&this.select(this.selectedIndex+1)},onViewMove:function(){this.inKeyMode=false},onViewOver:function(a,b){if(!this.inKeyMode)(a=this.view.findItemFromChild(b))&&this.select(this.view.indexOf(a),false)},onViewClick:function(a){var b=this.view.getSelectedIndexes()[0],c=this.store.getAt(b);c&&this.onSelect(c,b);a!==false&&this.el.focus()},onSelect:function(a,b){if(this.fireEvent("beforeselect",
this,a,b)!==false){this.replaceItemText(a.data[this.displayField]);this.collapse();this.fireEvent("select",this,a,b)}},getItemText:function(){var a=this.getRawValue(),b=this.el.dom.selectionStart,c=a.substr(0,b).lastIndexOf(this.itemSeparator)+1,d=a.substr(b).indexOf(this.itemSeparator);d=d<0?a.length:b+d;return a.substr(c,d-c)},replaceItemText:function(a){var b=this.getRawValue(),c=this.el.dom.selectionStart,d=b.substr(0,c).lastIndexOf(this.itemSeparator)+1,h=b.substr(c).indexOf(this.itemSeparator);
h=h<0?b.length:h+c+1;b=b.substr(0,d)+a+this.itemSeparator+b.substr(h);this.el.dom.selectionStart=d+a.length+1;this.setValue(b)},collapse:function(){if(this.isExpanded()){this.list.hide();Ext.getDoc().un("mousewheel",this.collapseIf,this);Ext.getDoc().un("mousedown",this.collapseIf,this);this.fireEvent("collapse",this)}},collapseIf:function(a){a.within(this.list)||this.collapse()},expand:function(){if(!(this.isExpanded()||!this.hasFocus)){this.list.alignTo(this.wrap,this.listAlign);this.list.show();
Ext.isGecko2&&this.innerList.setOverflow("auto");Ext.getDoc().on({scope:this,mousewheel:this.collapseIf,mousedown:this.collapseIf});this.fireEvent("expand",this)}},restrictHeight:function(){this.innerList.dom.style.height="";var a=this.innerList.dom,b=this.list.getFrameWidth("tb")+this.assetHeight;a=Math.max(a.clientHeight,a.offsetHeight,a.scrollHeight);var c=this.getPosition()[1]-Ext.getBody().getScroll().top,d=Ext.lib.Dom.getViewHeight()-c-this.getSize().height;c=Math.max(c,d,this.minHeight||0)-
this.list.shadowOffset-b-5;a=Math.min(a,c,this.maxHeight);this.innerList.setHeight(a);this.list.beginUpdate();this.list.setHeight(a+b);this.list.alignTo(this.wrap,this.listAlign);this.list.endUpdate()},onResize:function(a){Mixky.editor.EmailAddress.superclass.onResize.apply(this,arguments);if(this.list&&!Ext.isDefined(this.listWidth)){var b=Math.max(a,this.minListWidth);this.list.setWidth(b);this.innerList.setWidth(b-this.list.getFrameWidth("lr"))}}});Ext.reg("mixkyemailaddress",Mixky.editor.EmailAddress);Ext.namespace("Mixky.editor");
Mixky.editor.DeptTreeField=Ext.extend(Mixky.editor.PanelTriggerField,{confirm:true,minListWidth:300,maxHeight:500,minHeight:200,resizable:false,editable:false,selectMulti:false,selectType:"user",valueField:"key",displayField:"text",valueSeparator:";",valueFieldName:undefined,getRealValue:function(){var a=this.getValue(),b=this.findValueFieldCmp();if(b)a=b.getValue();return a},setRealValue:function(a){this.realValue=a;var b=this.findValueFieldCmp();b&&b.setValue(a);if(this.hiddenField)this.hiddenField.value=a},
findValueFieldCmp:function(){if(Ext.isDefined(this.valueFieldName)){var a=this.findParentByType("form");if(a)return a.getForm().findField(this.valueFieldName)}},onSelect:function(a,b,c){if(this.fireEvent("beforeselect",this,a,b,c)!==false){this.setValue(a);this.setRealValue(b);this.collapse();this.fireEvent("select",this,a,b,c)}},renderPanel:function(a){function b(f,e){e||(e=d.getRootNode());if(e.attributes[c.valueField]==f)if(Ext.isDefined(e.attributes.checked)){e.attributes.checked=true;e.getUI().toggleCheck(true)}e.eachChild(function(g){b(f,
g)})}var c=this,d=new Ext.tree.TreePanel({region:"center",autoScroll:true,rootVisible:false,style:"background-color:white",root:{nodeType:"async",text:"\u4eba\u5458\u9009\u62e9"},loader:new Ext.tree.TreeLoader({directFn:OrganizationAppDirect.getDeptTree,paramOrder:["type"],baseParams:{type:this.selectType},preloadChildren:true}),tools:[{id:"refresh",handler:function(){d.refresh()}}],refresh:function(){this.getRootNode().reload()}});d.getLoader().on("load",function(f,e){e.expand(true);if(Ext.isDefined(c.valueFieldName)){f=
c.findParentByType("form");if(Ext.isDefined(f)){f=f.getForm().findField(c.valueFieldName);Ext.isDefined(f.value)&&d.setValue(f.value)}}else Ext.isDefined(c.value)&&d.setValue(c.value)});d.on("checkchange",function(f,e){if(e&&!c.selectMulti){e=d.getChecked("id");for(var g=0;g<e.length;g++)e[g]!=f.id&&d.getNodeById(e[g]).getUI().toggleCheck(false)}});d.setValue=function(f){if(c.selectMulti){f=f.split(c.valueSeparator);for(var e=0;e<f.length;e++)b(f[e])}else b(f)};var h=[];if(this.confirm)h=[{text:"\u5237\u65b0",
iconCls:"icon-sys-refresh",handler:function(){d.refresh()}},"->",{text:"\u786e\u5b9a",iconCls:"icon-sys-confirm",handler:function(){var f=d.getChecked(c.valueField),e=d.getChecked(c.displayField),g="",i="";if(Ext.isDefined(f))for(var j=0;j<f.length;j++)if(j==0){g=f[j];i=e[j]}else{g=g+this.valueSeparator+f[j];i=i+";"+e[j]}this.onSelect(i,g);this.collapse()},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-sys-cancel",handler:function(){this.collapse()},scope:this}];return new Ext.Panel({renderTo:a,
layout:"fit",items:[new Ext.Panel({layout:"fit",height:300,items:[d],bbar:h})],beforeexpend:function(){d.setValue(c.getRealValue())}})}});Ext.reg("mixkydepttreefield",Mixky.editor.DeptTreeField);Ext.namespace("Mixky.editor");
Mixky.editor.DeptUserMultiSelectField=Ext.extend(Mixky.editor.PanelTriggerField,{confirm:true,editable:false,minListWidth:300,maxHeight:500,minHeight:200,resizable:true,selectMulti:true,selectType:"user",valueField:"id",displayField:"f_caption",valueSeparator:",",renderPanel:function(a){var b=this,c=new Ext.tree.TreePanel({region:"center",autoScroll:true,rootVisible:true,style:"background-color:white",root:{nodeType:"async",text:"\u4eba\u5458\u9009\u62e9"},loader:new Ext.tree.TreeLoader({directFn:OrganizationAppDirect.getUserTree,paramOrder:["type"],
baseParams:{type:""},preloadChildren:true}),tools:[{id:"refresh",handler:function(){c.refresh()}}],refresh:function(){this.getRootNode().reload()}}),d=new Ext.DataView({region:"south",autoScroll:true,split:true,height:80,minSize:50,maxSize:250,style:"background-color:white",tpl:new Ext.XTemplate('<tpl for=".">','<div class="user-expression-item icon-app-{type}" id="{expression}">{f_caption}</div>',"</tpl>",'<div class="x-clear"></div>'),selectedClass:"x-user-expression-view-selected",overClass:"x-user-expression-view-over",
itemSelector:"div.user-expression-item",multiSelect:false,plugins:[new Ext.DataView.DragSelector],store:new Ext.data.JsonStore({idProperty:"expression",fields:["expression","type","id","f_name","f_caption","f_note"]}),selectExpression:function(e){!b.selectMulti&&this.getStore().getCount()>0||OrganizationAppDirect.getExpressionData(e,b.selectType,function(g){for(var i=0;i<g.results.length;i++){var j=g.results[i];d.getStore().getById(j.expression)||d.getStore().loadData([g.results[i]],true)}})},loadSelectedUsers:function(e){this.clearSelected();
if(Ext.isDefined(e)&&e!=""){var g="";if(typeof e=="string")e=e.split(b.valueSeparator);for(var i=0;i<e.length;i++){if(i>0)g+=";";g+=e[i]}OrganizationAppDirect.loadSelectedUsers(b.selectType,b.valueField,g,function(j){d.getStore().loadData(j.results,true)})}},clearSelected:function(){d.getStore().removeAll()},removeSelected:function(){for(var e=d.getSelectedRecords(),g=0;g<e.length;g++)d.getStore().remove(e[g])}});d.contextMenu=new Ext.menu.Menu({items:[{text:"\u5220\u9664",iconCls:"icon-designtool-delete",
handler:function(){d.removeSelected()}}]});c.on("dblclick",function(e){e=e.attributes.expression;!e||e==""||!this.selectMulti&&this.selectType=="user"||d.selectExpression(e)});d.on("dblclick",function(){d.removeSelected()});d.on("contextmenu",function(e,g,i,j){e.contextMenu.showAt(j.getXY())});var h=new Ext.Panel({renderTo:a,layout:"border",border:false,items:[c,d]}),f=[];if(this.confirm)f=[{text:"\u5237\u65b0",iconCls:"icon-app-refresh",handler:function(){c.refresh()}},"->",{text:"\u786e\u5b9a",
iconCls:"icon-app-confirm",handler:function(){var e=d.getStore().getRange(),g="",i="";if(this.selectMulti&&this.valueSeparator=="")g=[];i="";for(var j=0;j<e.length;j++){if(j>0){i+=";";if(this.selectMulti&&this.valueSeparator!="")g+=this.valueSeparator}i+=e[j].get(this.displayField);if(this.selectMulti&&this.valueSeparator=="")g.push(e[j].get(this.valueField));else g+=e[j].get(this.valueField)}this.onSelect(i,g,e);this.collapse()},scope:this},"-",{text:"\u53d6\u6d88",iconCls:"icon-app-cancel",handler:function(){this.collapse()},
scope:this}];return new Ext.Panel({renderTo:a,layout:"fit",items:[new Ext.Panel({layout:"fit",height:300,items:[h],bbar:f})],beforeexpend:function(){if(b.selectType!=c.getLoader().baseParams.type){c.getLoader().baseParams.type=b.selectType;c.refresh()}d.loadSelectedUsers(b.realValue)}})}});Ext.reg("crcadeptusermultiselectfield",Mixky.editor.DeptUserMultiSelectField);