/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2013-01-28 07:40:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.app.mkoa.netfolder;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mixky.engine.organization.User;
import com.mixky.app.certification.MixkyUserCertification;
import com.mixky.app.mkoa.netfolder.FolderItem;

public final class view_folder_person_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String panelid = request.getParameter("panelid");
	User user = MixkyUserCertification.instance().getUserInfo(request);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language='javascript'>\r\n");
      out.write("\r\n");
      out.write("Ext.onReady(function(){\r\n");
      out.write("\r\n");
      out.write("\tvar panel = Ext.getCmp('");
      out.print(panelid);
      out.write("');\r\n");
      out.write("\r\n");
      out.write("\t// 数据访问\r\n");
      out.write("\tvar store = new Ext.data.DirectStore({\r\n");
      out.write("\t\tdirectFn : AppFolderDirect.getPersonalFolderList,\r\n");
      out.write("\t\tparamOrder:['folderId', 'userId'],\r\n");
      out.write("\t\tbaseParams:{folderId:0, userId:");
      out.print(user.getId());
      out.write("},\r\n");
      out.write("\t\troot : 'results',\r\n");
      out.write("\t\ttotalProperty : 'totals',\r\n");
      out.write("\t\tidProperty : 'ID',\r\n");
      out.write("\t\tfields:[\"F_NAME\",\"F_NOTE\",\"F_USERNAME\",\"F_CREATTIME\",\"F_SIZE\",\"F_ACTION\",\"ID\", \"F_TYPE\", \"F_PARENTID\", 'F_SHARETYPE', \"F_FILENAME\"]\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t// 显示列\r\n");
      out.write("\tvar columns = [\r\n");
      out.write("      \t{id:\"F_NAME\",header:\"名称\",dataIndex:\"F_NAME\",width:300, renderer : function(value, p, record){\r\n");
      out.write("\t\t\tvar type = 'icon-app-mkoa-folderup';\r\n");
      out.write("\t\t\tvar title = value;\r\n");
      out.write("\t\t\tswitch(record.get(\"F_TYPE\")){\r\n");
      out.write("\t\t\tcase 0:\r\n");
      out.write("\t\t\t\tif(record.get('F_SHARETYPE') == 0){\r\n");
      out.write("\t\t\t\t\ttype = 'icon-app-mkoa-folder';\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\ttype = 'icon-app-mkoa-foldershare';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 1:\r\n");
      out.write("\t\t\t\ttype = 'icon-app-mkoa-file';\r\n");
      out.write("\t\t\t\ttitle = '<a href=\"engine/file/sysdownload.do?documentdbtype=blob&fieldname=F_FILE&documentkey=mkNetFolder.docNetFile'\r\n");
      out.write("\t\t\t\t\t + '&id=' + record.get(\"ID\") + '&filename=' + record.get(\"F_FILENAME\") + '\">'\r\n");
      out.write("\t\t\t\t\t + title + '</a>';\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn String.format(\"<div style='padding-left:23px;background-repeat:no-repeat' class='{1}'> {0}</div>\", title, type);\r\n");
      out.write("\t\t}},\r\n");
      out.write("      \t{id:\"F_USERNAME\",header:\"创建人\",dataIndex:\"F_USERNAME\",width:80},\r\n");
      out.write("      \t{id:\"F_CREATTIME\",header:\"创建日期\",dataIndex:\"F_CREATTIME\",width:120},\r\n");
      out.write("      \t{id:\"F_SIZE\",header:\"文件大小\",dataIndex:\"F_SIZE\",width:80},\r\n");
      out.write("      \t{id:\"F_NOTE\",header:\"说明\",dataIndex:\"F_NOTE\"}\r\n");
      out.write("      ];\r\n");
      out.write("\r\n");
      out.write("    // 视图操作\r\n");
      out.write("    var AddFolderAction = new Ext.Action({\r\n");
      out.write("\t\ttext:'新建文件夹',\r\n");
      out.write("\t\ticonCls:'icon-sys-btnadd',\r\n");
      out.write("\t\thandler:function(){\r\n");
      out.write("    \t\tAppFolderDirect.getNewItemInfo(store.baseParams.folderId, store.baseParams.userId, function(result, e){\r\n");
      out.write("\t\t\t\tif(result) {\r\n");
      out.write("\t\t\t\t\tMixkyApp.desktop.openDocument('mkNetFolder.docNetFolder', 0, {'F_GRIDPANEL_ID':'");
      out.print(panelid);
      out.write("', 'F_PARENTID':result.f_parentid, 'F_LEVEL':result.f_level, 'F_BELONGUSERID':result.f_belonguserid, 'F_TYPE': ");
      out.print(FolderItem.TYPE_FOLDER);
      out.write("});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t        });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("    var UploadFileButton = new Mixky.plugins.UploadButton({\r\n");
      out.write("\t\ttext:'上传文件',\r\n");
      out.write("\t\ticonCls:'icon-sys-upload',\r\n");
      out.write("\t\tuploadConfig : {\r\n");
      out.write("\t\t\tupload_url : 'servlet/mkoa/netfolder/folderfile.upload',\r\n");
      out.write("\t\t\tpost_params : {\r\n");
      out.write("\t\t\t\tuserId: '");
      out.print(user.getId());
      out.write("'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tlisteners : {\r\n");
      out.write("\t\t\t\t'allUploadsComplete' : function(){\r\n");
      out.write("\t\t\t\t\tpanel.refreshView();\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t'startUpload' : function(){\r\n");
      out.write("\t\t\t\t\tthis.addPostParam('folderId', store.baseParams.folderId);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t// 刷新按钮\r\n");
      out.write("\tvar btnRefresh = new Ext.Action({\r\n");
      out.write("\t\ttext : '刷新',\r\n");
      out.write("\t\ticonCls : 'icon-sys-refresh',\r\n");
      out.write("\t\thandler : function(){\r\n");
      out.write("\t\t\tpanel.refresh();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tvar btnEdit = new Ext.Action({\r\n");
      out.write("\t\ttext: '编辑',\r\n");
      out.write("\t\ticonCls : 'icon-sys-edit',\r\n");
      out.write("\t\thandler: function() {\r\n");
      out.write("\t\t\tvar record = grid.getSelectionModel().getSelected();\r\n");
      out.write("\t\t\tvar windName;\r\n");
      out.write("\t\t\tif (record.get('F_TYPE') == 0) {\r\n");
      out.write("\t\t\t\tMixkyApp.desktop.openDocument('mkNetFolder.docNetFolder', record.get('ID'), {'F_GRIDPANEL_ID':'");
      out.print(panelid);
      out.write("'});\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tMixkyApp.desktop.openDocument('mkNetFolder.docNetFile', record.get('ID'), {'F_GRIDPANEL_ID':'");
      out.print(panelid);
      out.write("'});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\tvar btnDelete = new Ext.Action({\r\n");
      out.write("\t\ttext: '删除',\r\n");
      out.write("\t\ticonCls : 'icon-sys-delete',\r\n");
      out.write("\t\thandler: function() {\r\n");
      out.write("\t\t\tvar record = grid.getSelectionModel().getSelected();\r\n");
      out.write("\t\t\tif(!record){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar message = '';\r\n");
      out.write("\t\t\tif (record.get('F_TYPE') == ");
      out.print(FolderItem.TYPE_FOLDER);
      out.write(") {\r\n");
      out.write("\t\t\t\tmessage = \"删除文件夹【\" + record.get('F_NAME') + \"】，包括该文件夹下的所有子文件夹及文件，您确定吗？\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tmessage = \"删除文件【\" + record.get('F_NAME') + \"】，您确定吗？\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//添加confirm\r\n");
      out.write("\t\t\tExt.Msg.confirm('危险操作提示', message, function(btn) {\r\n");
      out.write("\t\t\t\tif (btn == 'yes') {\r\n");
      out.write("\t\t\t\t\tAppFolderDirect.deleteFolderItem(record.get('ID'), record.get('F_TYPE'));\r\n");
      out.write("\t\t\t\t\tpanel.refresh();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tvar fieldSearch = new Ext.form.TextField({\r\n");
      out.write("\t\twidth : 100,\r\n");
      out.write("\t\temptyText : '输入快速检索字符',\r\n");
      out.write("        listeners: {\r\n");
      out.write("\t        specialkey: function(field, e){\r\n");
      out.write("\t            // e.HOME, e.END, e.PAGE_UP, e.PAGE_DOWN,\r\n");
      out.write("\t            // e.TAB, e.ESC, arrow keys: e.LEFT, e.RIGHT, e.UP, e.DOWN\r\n");
      out.write("\t            if (e.getKey() == e.ENTER) {\r\n");
      out.write("\t            \tvar value = field.getValue();\r\n");
      out.write("\t    \t\t\tif(Ext.isDefined(value) && value != ''){\r\n");
      out.write("\t    \t\t\t\tvar modulePanel = MixkyApp.desktop.openModule('mkNetFolder');\r\n");
      out.write("\t    \t\t\t\tvar urlPanel  = modulePanel.openView('mkNetFolder.qFolder.vSearch');\r\n");
      out.write("\t    \t\t\t\tif(urlPanel){\r\n");
      out.write("\t    \t\t\t\t\tif(urlPanel.refresh){\r\n");
      out.write("\t    \t\t\t\t\t\turlPanel.refresh({folderId: store.baseParams.folderId,queryvalue: value});\r\n");
      out.write("\t    \t\t\t\t\t}else{\r\n");
      out.write("\t    \t\t\t\t\t\turlPanel.initParams = {folderId: store.baseParams.folderId,queryvalue: value};\r\n");
      out.write("\t    \t\t\t\t\t}\r\n");
      out.write("\t    \t\t\t\t}\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("\tvar btnSearch = new Ext.Action({\r\n");
      out.write("\t\ttext : '快速检索',\r\n");
      out.write("\t\ticonCls : 'icon-sys-query',\r\n");
      out.write("\t\thandler : function(){\r\n");
      out.write("\t\t\tvar value = fieldSearch.getValue();\r\n");
      out.write("\t\t\tif(Ext.isDefined(value) && value != ''){\r\n");
      out.write("\t\t\t\tvar modulePanel = MixkyApp.desktop.openModule('mkNetFolder');\r\n");
      out.write("\t\t\t\tvar urlPanel  = modulePanel.openView('mkNetFolder.qFolder.vSearch');\r\n");
      out.write("\t\t\t\tif(urlPanel){\r\n");
      out.write("\t\t\t\t\tif(urlPanel.refresh){\r\n");
      out.write("\t\t\t\t\t\turlPanel.refresh({folderId: store.baseParams.folderId,queryvalue: value});\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\turlPanel.initParams = {folderId: store.baseParams.folderId,queryvalue: value};\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tvar buttons = [{xtype: 'tbtext', text: ''},'->',fieldSearch, btnSearch, '-', AddFolderAction, '-',UploadFileButton, \"-\", btnEdit, btnDelete, '-', btnRefresh];\r\n");
      out.write("\r\n");
      out.write("\t//右键\r\n");
      out.write("\tvar contextmenus = [AddFolderAction, \"-\", btnEdit, btnDelete, '-', btnRefresh];\r\n");
      out.write("\r\n");
      out.write("\tvar sm = new Ext.grid.RowSelectionModel({singleSelect:true});\r\n");
      out.write("\r\n");
      out.write("\t// 表格对象\r\n");
      out.write("\tvar grid = new Ext.grid.GridPanel({\r\n");
      out.write("\t\tborder : false,\r\n");
      out.write("\t\tstripeRows: true,\r\n");
      out.write("\t\tenableHdMenu : true,\r\n");
      out.write("\t\tlineBreak : true,\r\n");
      out.write("\t\tcellSelect : false,\r\n");
      out.write("        loadMask: {msg:'正在装载...'},\r\n");
      out.write("\t\tautoExpandColumn : 'F_NOTE',\r\n");
      out.write("\t\tsm : sm,\r\n");
      out.write("\t\tcolumns : columns,\r\n");
      out.write("\t\tstore : store,\r\n");
      out.write("\t\ttbar : buttons,\r\n");
      out.write("\t\tcontextMenu : new Ext.menu.Menu({items:contextmenus}),\r\n");
      out.write("\t\tenableDragDrop : true,\r\n");
      out.write("\t\tddGroup : 'grid2tree',\r\n");
      out.write("\t\tlisteners:{\r\n");
      out.write("\t\t\trowcontextmenu:function(grid, rowIndex, e){\r\n");
      out.write("        \t    grid.getSelectionModel().selectRow(rowIndex);\r\n");
      out.write("\t\t\t\tif(this.contextMenu.items.length > 0){\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\tif (rowIndex == 0 && store.baseParams.folderId > 0) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tthis.contextMenu.showAt(e.getXY());\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\trowdblclick:function(grid, index, e){\r\n");
      out.write("\t\t\t\tvar record = grid.store.getAt(index);\r\n");
      out.write("\t\t\t\tif (record.get('F_TYPE') == 0) {\r\n");
      out.write("\t\t\t\t\tstore.baseParams.folderId = record.get('ID');\r\n");
      out.write("\t\t\t\t\tpanel.refreshTree(false);\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tlocation.href = 'engine/file/sysdownload.do?documentdbtype=blob&fieldname=F_FILE&documentkey=mkNetFolder.docNetFile'\r\n");
      out.write("\t\t\t\t\t\t\t + '&id=' + record.get(\"ID\") + '&filename=' + record.get(\"F_FILENAME\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tgetSelectedRecords : function(){\r\n");
      out.write("\t\t\treturn this.getSelectionModel().getSelections();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getSelectedRecords(){\r\n");
      out.write("\t\treturn grid.getSelectedRecords();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 视图刷新\r\n");
      out.write("\tpanel.refresh = function(params){\r\n");
      out.write("\t\tif(Ext.isDefined(params) && Ext.isDefined(params.folderId)){\r\n");
      out.write("\t\t\tstore.baseParams.folderId = parseInt(params.folderId);\r\n");
      out.write("\t\t\tif(store.baseParams.folderId > 0){\r\n");
      out.write("\t\t\t\tUploadFileButton.enable();\r\n");
      out.write("\t\t\t\tAppFolderDirect.getPersonalFolderFullPath(store.baseParams.folderId, function(result, e){\r\n");
      out.write("\t\t\t\t\tif(result && result.success) {\r\n");
      out.write("\t\t\t\t\t\tgrid.getTopToolbar().get(0).setText('个人文件柜' + result.fullPath);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(store.baseParams.folderId == 0){\r\n");
      out.write("\t\t\tUploadFileButton.disable();\r\n");
      out.write("\t\t\tgrid.getTopToolbar().get(0).setText('个人文件柜');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t// 初始化参数\r\n");
      out.write("\t\tstore.reload();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tpanel.add(grid);\r\n");
      out.write("\tpanel.doLayout();\r\n");
      out.write("\t// 初始化视图数据\r\n");
      out.write("\tpanel.refresh(panel.initParams);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("    //为左边菜单添加文件夹移动事件\r\n");
      out.write("\tExt.getCmp('m-mkNetFolder').items.items[0].moduleTree.addListener('beforenodedrop', function(e) {\r\n");
      out.write("\t\tif(Ext.isArray(e.data.selections)) {\r\n");
      out.write("\t\t\tvar r;\r\n");
      out.write("            for(var i = 0; i < e.data.selections.length; i++) {\r\n");
      out.write("\t            r = e.data.selections[i];\r\n");
      out.write("\t            var targetId;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (e.target.attributes.folderId && e.target.attributes.folderId != null) {\r\n");
      out.write("\t\t\t\t\ttargetId = e.target.attributes.folderId;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t//拖入到个人文件柜的目录下\r\n");
      out.write("\t\t\t\t\tif (e.target.id  == Ext.getCmp('m-mkNetFolder').items.items[0].moduleTree.getRootNode().firstChild.id) {\r\n");
      out.write("\t\t\t\t\t\tif (r.get('F_TYPE') == ");
      out.print(FolderItem.TYPE_FILE);
      out.write(") {\r\n");
      out.write("\t\t\t\t\t\t\tExt.Msg.alert('信息提示', '文件移动，只能移动到自定义的文件夹下！');\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\ttargetId = 0;\r\n");
      out.write("\t\t\t\t\t//拖入到其它根目录，直接返回\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tExt.Msg.alert('信息提示', '文件和文件夹的移动，只能移动到个人文件柜下！');\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (targetId == r.get('F_PARENTID')) {\r\n");
      out.write("\t\t\t\t\tExt.Msg.alert('信息提示', r.get('F_NAME') + '已经在' + e.target.text + '文件夹下！');\r\n");
      out.write("\t\t\t\t\treturn false; \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (targetId == r.get('ID')) {\r\n");
      out.write("\t\t\t\t\tExt.Msg.alert('信息提示', r.get('F_NAME') + '不允许移动到' + e.target.text + '文件夹下！');\r\n");
      out.write("\t\t\t\t\treturn false; \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tAppFolderDirect.moveFolderItem(r.get('ID'), targetId, function(result, event) {\r\n");
      out.write("\t\t\t\t\tif (result) {\r\n");
      out.write("\t\t\t\t\t\tif (result.success) {\r\n");
      out.write("\t\t\t\t\t\t\tif (store.baseParams.folderId == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\tExt.getCmp('m-mkNetFolder').items.items[0].moduleTree.getRootNode().firstChild.reload();\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\te.target.reload();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t//Ext.getCmp('m-mkNetFolder').items.items[0].moduleTree.getRootNode().firstChild.reload();\r\n");
      out.write("\t\t\t\t\t\t\tpanel.refreshViewAndTree();\r\n");
      out.write("\t\t\t\t\t\t\tpanel.refresh();\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t//不允许移动到指定目录\r\n");
      out.write("\t\t\t\t\t\t\tExt.Msg.alert('信息提示', r.get('F_NAME') + '不允许移动到' + e.target.text + '文件夹下！');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, this);\r\n");
      out.write("            }\r\n");
      out.write(" \r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//表单保存后刷新视图列表和菜单\r\n");
      out.write("\tpanel.refreshViewAndTree = function() {\r\n");
      out.write("\t\tpanel.refreshTree(true);\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tpanel.refreshView = function() {\r\n");
      out.write("\t\tpanel.refresh();\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tpanel.refreshTree = function(refreshflag) {\r\n");
      out.write("\t\tvar rootNode = Ext.getCmp('m-mkNetFolder').items.items[0].moduleTree.getRootNode();\r\n");
      out.write("\t\tif (store.baseParams.folderId == 0) {\r\n");
      out.write("\t\t\trootNode.firstChild.select();\r\n");
      out.write("\t\t\t//rootNode.firstChild.reload();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tAppFolderDirect.getPersonalFolderFullPath(store.baseParams.folderId, function(result, e){\r\n");
      out.write("\t\t\t\tif(result && result.success) {\r\n");
      out.write("\t\t\t\t\tExt.getCmp('m-mkNetFolder').items.items[0].moduleTree.expandPath(rootNode.firstChild.getPath('text') + result.fullPath, 'text', function(success, lastNode){\r\n");
      out.write("\t\t\t\t\t\tif (success) {\r\n");
      out.write("\t\t\t\t\t\t\tif (refreshflag) {\r\n");
      out.write("\t\t\t\t\t\t\t\tlastNode.reload();\r\n");
      out.write("\t\t\t\t\t\t\t\tlastNode.select();\r\n");
      out.write("\t\t\t\t\t\t\t\tpanel.refresh();\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\tlastNode.select();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t        });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
