/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2013-01-29 06:52:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.app.mkoa.workreport;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mixky.engine.organization.User;
import com.mixky.app.certification.MixkyUserCertification;
import com.mixky.engine.view.View;
import com.mixky.engine.common.Action;
import com.mixky.engine.view.ViewManager;
import com.mixky.engine.authority.AuthorityManager;
import java.util.List;

public final class workreport_detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String panelid = request.getParameter("panelid");
	View view = (View)request.getAttribute("view");

	User user = MixkyUserCertification.instance().getUserInfo(request);
	List<Action> actions = AuthorityManager.instance().getDesignObjectsByUser(view.getF_buttons(), user);


      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language='javascript'>\r\n");
      out.write("\r\n");
      out.write("Ext.onReady(function(){\r\n");
      out.write("\r\n");
      out.write("\tvar panel = Ext.getCmp('");
      out.print(panelid);
      out.write("');\r\n");
      out.write("\r\n");
      out.write("\t// 数据访问\r\n");
      out.write("\tvar store = new Ext.data.DirectStore({\r\n");
      out.write("\t\tdirectFn : AppWorkReportDirect.getWorkReportDetail,\r\n");
      out.write("\t\tparamOrder:['id'],\r\n");
      out.write("\t\tbaseParams:{id:0},\r\n");
      out.write("\t\troot : 'results',\r\n");
      out.write("\t\ttotalProperty : 'totals',\r\n");
      out.write("\t\tidProperty : 'ID',\r\n");
      out.write("\t\tfields:[\"ID\",\"F_TITLE\",\"F_CREATOR_NAME\",\"F_CREATED\",\"F_CONTENT\", \"F_CREATOR_DEPT\", \"F_SCOPS\", \"F_FILES\"]\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tvar comentStore = new Ext.data.DirectStore({\r\n");
      out.write("\t\tdirectFn : AppWorkReportDirect.getWorkReportComments,\r\n");
      out.write("\t\tparamOrder:['id'],\r\n");
      out.write("\t\tbaseParams:{id:0},\r\n");
      out.write("\t\troot : 'results',\r\n");
      out.write("\t\ttotalProperty : 'totals',\r\n");
      out.write("\t\tidProperty : 'ID',\r\n");
      out.write("\t\tfields:[\"ID\",\"F_CREATOR_NAME\",\"F_CREATED\",\"F_CONTENT\", \"F_POSITION\"]\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t// 视图操作\r\n");
      out.write("\t");

		for(int i=0;i<actions.size();i++){
			Action action = actions.get(i);
	
      out.write("\r\n");
      out.write("\t\tvar ");
      out.print(action.getF_key());
      out.write(" = new Ext.Action({\r\n");
      out.write("\t\t\ttext : '");
      out.print(action.getF_caption());
      out.write("',\r\n");
      out.write("\t\t\ticonCls : '");
      out.print(action.getIcon());
      out.write("',\r\n");
      out.write("\t\t\tisDefault : ");
      out.print(action.getF_default());
      out.write(",\r\n");
      out.write("\t");

			if(action.getF_handler() == null || "".equals(action.getF_handler())){
	
      out.write("\r\n");
      out.write("\t\t\thandler : Ext.emptyFn\r\n");
      out.write("\t");

			}else{
	
      out.write("\r\n");
      out.write("\t\t\thandler : ");
      out.print(action.getF_handler());
      out.write('\r');
      out.write('\n');
      out.write('	');

			}
	
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t// 刷新按钮\r\n");
      out.write("\tvar btnRefresh = new Ext.Action({\r\n");
      out.write("\t\ttext : '刷新',\r\n");
      out.write("\t\ticonCls : 'icon-sys-refresh',\r\n");
      out.write("\t\thandler : function(){\r\n");
      out.write("\t\t\tpanel.refresh();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tvar buttons = ");
      out.print(ViewManager.instance().getViewButtonNames(view, actions));
      out.write(";\r\n");
      out.write("\r\n");
      out.write("\tvar html = '<tpl for=\".\">' \r\n");
      out.write("\t\t\t\t+ '<div class=\"x-forum-thread-detail\"><div class=\"x-forum-thread-inner\"><div class=\"x-forum-thread-header\">' \r\n");
      out.write("\t\t\t\t\t+ '<table width=\"100%\"><tbody><tr><td>' \r\n");
      out.write("\t\t\t\t\t\t+ '<div class=\"x-forum-thread-header-info\"><b>&nbsp;正文</b>&nbsp;&nbsp;{F_CREATOR_DEPT}&nbsp;&nbsp;{F_CREATOR_NAME}({F_CREATED})</div>' \r\n");
      out.write("\t\t\t\t\t+ '</td><td class=\"x-forum-thread-header-tool\">' \r\n");
      out.write("\t\t\t\t\t\t+ '<tpl if=\"false == true\"><img class=\"x-forum-thread-header-tool-edit\" src=\"\"></img><img class=\"x-forum-thread-header-tool-delete\" src=\"\"></img></tpl>' \r\n");
      out.write("\t\t\t\t\t+ '</td></tr></tbody></table>' \r\n");
      out.write("\t\t\t\t+ '</div><div class=\"x-forum-thread-body\"><div class=\"x-forum-thread-body-inner\">' \r\n");
      out.write("\t\t\t\t+ '<div class=\"x-knowledge-thread-title\"><b>{F_TITLE}</b></div><div class=\"x-knowledge-thread-tag\">发布范围：{F_SCOPS}</div>' \r\n");
      out.write("\t\t\t\t+ '<div class=\"x-forum-thread-desc\">{F_CONTENT}</div>'\r\n");
      out.write("\t\t\t\t+ '<tpl for=\"F_FILES\"><div class=\"x-forum-thread-attach\"><img class=\"function-file-download\" src=\"resources/images/app/forum/attach.png\" style=\"cursor:pointer\"></img><a class=\"x-forum-thread-attach-link\" href=\"#\" onclick=\"Ext.getCmp(\\'");
      out.print(panelid);
      out.write("\\').downloadFile({ID});\"><b>{F_NAME}</b></a></div></tpl>' \r\n");
      out.write("\t\t\t\t//+ '<div class=\"x-forum-thread-footer\"><input class=\"x-forum-thread-footer-quote\" type=\"button\" value=\"引用\" /></div>' \r\n");
      out.write("\t\t\t\t+ '</div></div></div></div>' \r\n");
      out.write("\t\t\t\t+ '</tpl><div class=\"x-clear\"></div>';\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    var tpl=new Ext.XTemplate(html);\r\n");
      out.write("\r\n");
      out.write("\tvar dataView=new Ext.DataView({\r\n");
      out.write("\t\tstore:store,\r\n");
      out.write("\t\ttpl:tpl,\r\n");
      out.write("\t\titemSelector:\"div.x-forum-thread-detail\",\r\n");
      out.write("\t\t//selectedClass: '',\r\n");
      out.write("\t\tsingleSelect:true\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tvar commentHtml = '<tpl for=\".\">' \r\n");
      out.write("\t\t+ '<div class=\"x-forum-thread-detail\"><div class=\"x-forum-thread-inner\"><div class=\"x-forum-thread-header\">' \r\n");
      out.write("\t\t\t+ '<table width=\"100%\"><tbody><tr><td>' \r\n");
      out.write("\t\t\t\t+ '<div class=\"x-forum-thread-header-info\"><b>&nbsp;# {F_POSITION}</b>&nbsp;&nbsp;{F_CREATOR_NAME}({F_CREATED})</div>' \r\n");
      out.write("\t\t\t+ '</td><td class=\"x-forum-thread-header-tool\">' \r\n");
      out.write("\t\t\t\t+ '<tpl if=\"false == true\"><img class=\"x-forum-thread-header-tool-edit\" src=\"\"></img><img class=\"x-forum-thread-header-tool-delete\" src=\"\"></img></tpl>' \r\n");
      out.write("\t\t\t+ '</td></tr></tbody></table>' \r\n");
      out.write("\t\t+ '</div><div class=\"x-forum-thread-body\"><div class=\"x-forum-thread-body-inner\">' \r\n");
      out.write("\t\t//+ '<div class=\"x-forum-thread-author\"><b>{F_CREATOR_NAME}</b></div>' \r\n");
      out.write("\t\t+ '<div class=\"x-forum-thread-desc\">{F_CONTENT}</div>'\r\n");
      out.write("\t\t//+ '<tpl if=\"false == true\"><div class=\"x-forum-thread-attach\"><img class=\"function-file-download\" src=\"images/icons/attach.png\" style=\"cursor:pointer\"></img><a class=\"x-forum-thread-attach-link\" href=\"#\">Download attached file <b></b></a></div></tpl>' \r\n");
      out.write("\t\t+ '</div></div></div></div>' \r\n");
      out.write("\t\t+ '</tpl><div class=\"x-clear\"></div>';\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar commentTpl=new Ext.XTemplate(commentHtml);\r\n");
      out.write("\t\r\n");
      out.write("\tvar commentDataView=new Ext.DataView({\r\n");
      out.write("\t\tstore:comentStore,\r\n");
      out.write("\t\ttpl:commentTpl,\r\n");
      out.write("\t\titemSelector:\"div.x-forum-thread-detail\",\r\n");
      out.write("\t\tsingleSelect:true\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("    var fViewPanel = new Ext.Panel({\r\n");
      out.write("        border:false,\r\n");
      out.write("    \tregion:'center',\r\n");
      out.write("\t\ttbar:buttons,\r\n");
      out.write("\t\tautoScroll:true,\r\n");
      out.write("\t\titems:[dataView, commentDataView]\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    panel.downloadFile = function(id) {\r\n");
      out.write("\t\tlocation.href = \"engine/file/sysdownload.do?id=\" + id + \"&documentdbtype=none&fieldname=F_FILES&documentkey=mkKnowledge.DocKnowledgeDetail\";\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tstore.on('load', function(s, rs){\r\n");
      out.write("\t\tvar r = rs[0];\r\n");
      out.write("\t\tpanel.setTitle(Ext.util.Format.ellipsis(r.get('F_TITLE'), 15));\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t// 视图刷新\r\n");
      out.write("\tpanel.refresh = function(params){\r\n");
      out.write("\t\tif(Ext.isDefined(params)){\r\n");
      out.write("\t\t\tpanel.params = params;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t// 初始化参数\r\n");
      out.write("\t\tstore.baseParams.id = parseInt(panel.params.id);\r\n");
      out.write("\t\tcomentStore.baseParams.id = parseInt(panel.params.id);\r\n");
      out.write("\t\tstore.load();\r\n");
      out.write("\t\tcomentStore.load();\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t/**按钮逻辑*/\r\n");
      out.write("\r\n");
      out.write("\t// 输出附加脚本 begin\r\n");
      out.write("\r\n");
      out.write("\t// 输出附加脚本 end\r\n");
      out.write("\tpanel.add(fViewPanel);\r\n");
      out.write("\tpanel.doLayout();\r\n");
      out.write("\t// 初始化视图数据\r\n");
      out.write("\tpanel.refresh(panel.initParams);\r\n");
      out.write("  \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
