/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2013-02-19 02:07:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.designtool;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String applicationName = "创想天空协作平台";
	Object obj = request.getAttribute("applicationName");
	if (obj != null){
		applicationName = String.valueOf(obj);
	}

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar _globe_ApplicationName_ = '");
      out.print(applicationName);
      out.write("';\r\n");
      out.write("</script>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t\t<title>");
      out.print(applicationName);
      out.write(" - 开发管理工具</title>\r\n");
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../dependences/ext-3.1.1/resources/css/ext-all.css\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"designtool.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"designtool.icon.css\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/js/editor/mixky.user.selector.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/ux/roweditor.3.1.1/roweditor.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../dependences/ext-3.1.1/adapter/ext/ext-base.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../dependences/ext-3.1.1/ext-all-debug.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../dependences/ext-3.1.1/src/locale/ext-lang-zh_CN.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"api.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- SWFUpload Include -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../dependences/swfupload/swfupload.js\"></script>\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/editor/mixky.paneltriggerfield.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/editor/mixky.textbox.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/editor/mixky.organization.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/editor/mixky.designobject.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/editor/mixky.jsonobject.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/editor/mixky.user.selector.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/plugin/mixky.propertygrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/plugin/mixky.rowordercolumn.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/plugin/mixky.editor.rownumberer.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/plugin/mixky.organization.window.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/ux/roweditor.3.1.1/roweditor.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/ux/tabclosemenu/tabclosemenu.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/ux/dataviewmore/dataviewmore.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/ux/checkcolumn/checkcolumn.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/ux/uploaddialog/ext.swf.uploaddialog.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../dependences/googlechart/jsapi\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../dependences/googlechart/default,orgchart.I.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../dependences/googlechart/orgchart.css\"/>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/ux/chart/GVisualizationPanel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/mixky.lib.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"designtool.lib.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"designtool.context.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"designtool.head.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"designtool.tree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"designtool.main.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"designtool.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"designtool.action.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"designtool.class.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Sets the basepath for the library if not in same directory -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tmxBasePath = '../dependences/mxgraph/src';\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Loads and initiaizes the library -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../dependences/mxgraph/mxclient.1.4.0.9.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"loading-mask\" style=\"\"></div>\r\n");
      out.write("\t\t<div id=\"loading\">\r\n");
      out.write("\t\t\t<div class=\"loading-indicator\"><img src=\"extanim32.gif\" width=\"32\" height=\"32\" style=\"margin-right:8px;\" align=\"absmiddle\"/>正在装载界面，请稍候...</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"designtool-head\">\r\n");
      out.write("\t\t\t");
      out.print(applicationName);
      out.write(" - 开发管理工具\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=designtool-outline></div>\r\n");
      out.write("\t\t<div id=designtool-content></div>\r\n");
      out.write("\t\t<div id=designtool-attribute></div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
