/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2013-01-24 07:48:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.app.mkoa.mail;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mixky.app.mkoa.mail.Mail;
import com.mixky.app.mkoa.mail.MailManager;
import javax.mail.internet.MimeMessage;
import com.mixky.app.mkoa.mail.util.MessageUtil;
import java.util.List;
import java.util.ArrayList;
import com.mixky.app.mkoa.mail.MailPart;
import com.mixky.system.ContextHolder;
import com.garage.xtoolkit.HTMLHelper;
import com.mixky.toolkit.DateUtil;
import com.mixky.app.mkoa.mail.util.MailUtility;

public final class mail_show_details_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String id = request.getParameter("id");
	String panelid = request.getParameter("panelid");
	
	Mail mail = MailManager.instance().getMailById(Long.parseLong(id));
	MimeMessage msg = MessageUtil.getMsgByMailObj(mail);
	
	if (msg != null) {	
		
		List<MailPart> emailList = new ArrayList<MailPart>();
		List<MailPart> attList = new ArrayList<MailPart>();
		List<MailPart> imgList = new ArrayList<MailPart>();
		
		String mailFilePath = ContextHolder.instance().getRealPath("WEB-INF/mailtmp");
		String mailFileURL = "mailtmp";
		MessageUtil.fetchParts(msg, mailFilePath, emailList, attList, imgList);
		//MessageUtil.parseImgPath(emailList, imgList, mailFileURL);
	

      out.write("\n");
      out.write("\n");
      out.write("<DIV id='");
      out.print(panelid);
      out.write("-table'>\n");
      out.write("<input type=hidden id='");
      out.print(panelid);
      out.write("-maildetail' value='");
      out.print(MessageUtil.getMailHead(msg));
      out.write("'>\n");
      out.write("<input type=hidden id='");
      out.print(panelid);
      out.write("-emllocation' value='");
      out.print(mail.getF_location());
      out.write("'>\n");
      out.write("<input type=hidden id='");
      out.print(panelid);
      out.write("-emlname' value='");
      out.print(mail.getF_subject() + ".eml");
      out.write("'>\n");
      out.write("<TABLE cellSpacing=0 cellPadding=0 align=center bgColor=white width=100% height=100% >\n");
      out.write("\t<TR style=\"HEIGHT: 6px\" height=6>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/t_l.gif'></TD>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/t_z.gif'></TD>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/t_y.gif'></TD>\n");
      out.write("\t<TR>\n");
      out.write("\t\t<TD vAlign=top width=2 background='resources/images/report/b_l.gif'></TD>\n");
      out.write("\t\t<TD style=\"padding:20px;padding-top:0px\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<TABLE  cellSpacing=0 cellPadding=0 width=100% height=100% style='font-size:13px;'>\n");
      out.write("\t\t\t\t<tr><td colspan=2 height=\"10\"></td></tr>\n");
      out.write("\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t<TD width=60 style='font-size:12px;'>\n");
      out.write("\t\t\t\t\t\t发件人：\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD style='font-size:12px;'>\n");
      out.write("\t\t\t\t\t\t");
      out.print(HTMLHelper.encode(MessageUtil.decodeString(MessageUtil.addressArrToString(msg.getFrom()))));
      out.write("　<a href=\"#\" onclick=\"AddressBookAppDirect.isMailFromExist('");
      out.print(HTMLHelper.encode(MessageUtil.decodeString(MessageUtil.addressArrToString(msg.getFrom()))));
      out.write("', function(result, event) {if (result.success) { MixkyApp.desktop.openDocument('mkAddressBook.docNameCard', 0, {F_NAME:result.name, F_EMAIL: result.email}); } else {MixkyApp.showInfoMessage('发件人已个人通讯录中', '信息提示');}})\">添加到个人通讯录</a>\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t<TD width=60 style='font-size:12px;'>\n");
      out.write("\t\t\t\t\t\t发送至：\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD style='font-size:12px;'><textarea readonly=true style='width:100%;text-align:left'>\n");
      out.write("\t\t\t\t\t\t");
      out.print(HTMLHelper.encode(MessageUtil.getValueByHeader(msg, "TO")));
      out.write("</textarea>\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\n");

	if (MessageUtil.getValueByHeader(msg, "CC").length() > 0) {

      out.write("  \n");
      out.write("\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t<TD width=60 style='font-size:12px;'>\n");
      out.write("\t\t\t\t\t\t抄送：\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD style='font-size:12px;'>\n");
      out.write("\t\t\t\t\t\t");
      out.print(HTMLHelper.encode(MessageUtil.getValueByHeader(msg, "CC")));
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");

	}

      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t<TD width=60 style='font-size:12px;'>\n");
      out.write("\t\t\t\t\t\t日　期：\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD style='font-size:12px;'>\n");
      out.write("\t\t\t\t\t\t");
      out.print(DateUtil.format(mail.getF_date_received(), DateUtil.FORMAT_DATETIME));
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t<TD width=60 style='font-size:12px;'>\n");
      out.write("\t\t\t\t\t\t主　题：\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD style='font-size:12px;'>\n");
      out.write("\t\t\t\t\t\t");
      out.print(msg.getSubject() == null ? "" : MessageUtil.decodeString(msg.getSubject()));
      out.write(" \n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t<TD width=60 style='font-size:12px;'>\n");
      out.write("\t\t\t\t\t\t附　件：\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD style='font-size:12px;'>\n");

		for (int i = 0; i < attList.size(); i++) {
			MailPart attPart = (MailPart) attList.get(i);
			String fileUrl = "mkoa/mail/mailfile.download.do?filename=" + attPart.getFileName() + "&filelocation=" + attPart.getFilePath();

      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t");
      out.print("<a href=\"" + fileUrl + "\">" + attPart.getFileName() + "</a>&nbsp;&nbsp;&nbsp;&nbsp;");
      out.write('	');
      out.write('	');
      out.write('\n');
			
		}

      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t<tr><td colspan=2 height=\"10\"></td></tr>\n");
      out.write("\t\t\t\t<tr><td colspan=2 height=\"1\" bgcolor=\"#d6d6d6\"></td></tr>\n");
      out.write("\t\t\t\t<tr><td colspan=2 height=\"10\"></td></tr>\n");
      out.write("\t\t\t\t<tr><td colspan=2 height=100% valign=top>\n");

		if (emailList.size() > 0) {
			String strangeContent = null;
			if (emailList.size() > 2) {
				MailPart strangePart = (MailPart) emailList.get(0);
				strangeContent = strangePart.getContent();
			}
			MailPart contentPart = (MailPart) emailList.get(emailList.size() - 1);
			if (contentPart.getContentType().startsWith("text/html")) {

      out.write("\n");
      out.write("\t\t\t\t");
      out.print(contentPart.getContent());
      out.write('	');
      out.write('\n');
 
			} else {

      out.write("\n");
      out.write("\t\t\t\t\t");
      out.print(strangeContent == null ? MailUtility.getHtmlString(contentPart.getContent()) : MailUtility.getHtmlString(strangeContent));
      out.write('	');
      out.write('\n');

			}
		}

      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t<br/><br/>\n");
      out.write("\t\t\t\t\n");

		for (int i = 0; i < attList.size(); i++) {
			MailPart attPart = (MailPart) attList.get(i);
			if (attPart.getContentType().toLowerCase().startsWith("image")) {
				String fileUrl = "mkoa/mail/mailfile.download.do?filetype=image&filename=" + attPart.getFileName() + "&filelocation=" + attPart.getFilePath();

      out.write("\n");
      out.write("\t\t\t\t<image title=\"");
      out.print(attPart.getFileName());
      out.write("\" src=\"");
      out.print(fileUrl);
      out.write("\" class=\"mixky-detail-image\"/><br/>\n");
      out.write("\t\t\t\t");
      out.print("<a href=\"" + fileUrl + "\">" + attPart.getFileName() + "</a><br/><br/>");
      out.write('\n');
		
			}
		}

      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</td></tr>\n");
      out.write("\t\t\t</TABLE>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</TD>\n");
      out.write("\t\t<TD vAlign=top width=3 background='resources/images/report/b_y.gif'></TD>\n");
      out.write("\t</TR>\n");
      out.write("\t<TR style=\"HEIGHT: 7px\" height=7>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/d_l.gif'></TD>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/d_z.gif'></TD>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/d_y.gif'></TD>\n");
      out.write("\t</TR>\n");
      out.write("</TABLE>\n");
      out.write("</DIV>\n");
      out.write("\n");
 
	} else {

      out.write("\n");
      out.write("<DIV id='");
      out.print(panelid);
      out.write("-table'>\n");
      out.write("<TABLE cellSpacing=0 cellPadding=0 align=center bgColor=white width=100% height=100% >\n");
      out.write("\t<TR style=\"HEIGHT: 6px\" height=6>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/t_l.gif'></TD>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/t_z.gif'></TD>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/t_y.gif'></TD>\n");
      out.write("\t<TR>\n");
      out.write("\t\t<TD vAlign=top width=2 background='resources/images/report/b_l.gif'></TD>\n");
      out.write("\t\t<TD style=\"padding:20px;padding-top:0px\">\n");
      out.write("\t\t\t<TABLE  cellSpacing=0 cellPadding=0 width=100% height=100% style='font-size:13px;'>\n");
      out.write("\t\t\t\t<tr><td  height=100% valign=top>\n");
      out.write("\t\t\t\t\t邮件解析失败！\n");
      out.write("\t\t\t\t</td></tr>\n");
      out.write("\t\t\t</TABLE>\n");
      out.write("\t\t</TD>\n");
      out.write("\t\t<TD vAlign=top width=3 background='resources/images/report/b_y.gif'></TD>\n");
      out.write("\t</TR>\n");
      out.write("\t<TR style=\"HEIGHT: 7px\" height=7>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/d_l.gif'></TD>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/d_z.gif'></TD>\n");
      out.write("\t\t<TD vAlign=top background='resources/images/report/d_y.gif'></TD>\n");
      out.write("\t</TR>\n");
      out.write("</TABLE>\n");
      out.write("</DIV>\n");
		
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
