/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2013-02-20 04:06:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.app.mkoa.forum;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.google.gson.JsonObject;
import com.mixky.engine.view.View;
import com.mixky.engine.view.ViewManager;
import com.mixky.engine.view.Column;
import com.mixky.engine.common.Action;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String panelid = request.getParameter("panelid");
	View view = (View)request.getAttribute("view");
	List<Column> columns = view.getF_columns();
	List<Action> actions = view.getF_buttons();
	JsonObject cfg = view.getF_config();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language='javascript'>\r\n");
      out.write("Ext.onReady(function(){\r\n");
      out.write("\r\n");
      out.write("\tvar panel = Ext.getCmp('");
      out.print(panelid);
      out.write("');\r\n");
      out.write("\r\n");
      out.write("\tvar subpanel = new Ext.Panel({\r\n");
      out.write("\t\tborder : false,\r\n");
      out.write("\t\tautoScroll : true,\r\n");
      out.write("\t\tlayout : 'fit'\r\n");
      out.write("\t});\r\n");
      out.write("\t// 获得视图页面对象\r\n");
      out.write("\tsubpanel.getViewPanel = function(){\r\n");
      out.write("\t\treturn panel;\r\n");
      out.write("\t}\r\n");
      out.write("\t// 装载子页面\r\n");
      out.write("\tpanel.loadUrl = function(type){\r\n");
      out.write("\t\tvar params = {panelid : subpanel.getId()};\r\n");
      out.write("\t\tif(Ext.isDefined(panel.initParams)){\r\n");
      out.write("\t\t\t// TODO:\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tparams.viewkey = '';\r\n");
      out.write("\t\tif (type == 'forum-home') {\r\n");
      out.write("\t\t\tparams.url = \"app/mkoa/forum/forum.home\";\r\n");
      out.write("\t\t} else if (type == 'forum-forums') {\r\n");
      out.write("\t\t\tparams.url = \"app/mkoa/forum/forum.subject.home\";\r\n");
      out.write("\t\t} else if (type == 'forum-subjects') {\r\n");
      out.write("\t\t\tparams.url = \"app/mkoa/forum/forum.subjects\";\r\n");
      out.write("\t\t\tparams.forumId = panel.initParams.forumId;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tsubpanel.removeAll();\r\n");
      out.write("\t\tsubpanel.load({\r\n");
      out.write("\t\t\turl : \"framework/engine/view/view.do\",\r\n");
      out.write("\t\t\tparams : params,\r\n");
      out.write("\t\t\tscripts : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t// 视图刷新\r\n");
      out.write("\tpanel.refresh = function(params){\r\n");
      out.write("\t\tif(Ext.isDefined(params)){\r\n");
      out.write("\t\t\tpanel.initParams = params;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tparams = panel.initParams;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar type = 'forum-home';\r\n");
      out.write("\t\tif (params && params.forumId > 0) {\r\n");
      out.write("\t\t\ttype = 'forum-subjects';\r\n");
      out.write("\t\t} else if (params && params.categoryId > 0) {\r\n");
      out.write("\t\t\ttype = 'forum-forums';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tpanel.enable();\r\n");
      out.write("\t\tif (Ext.isDefined(subpanel.refresh)) {\r\n");
      out.write("\t\t\t//subpanel.refresh(params);\r\n");
      out.write("\t\t\tsubpanel.initParams = panel.initParams;\r\n");
      out.write("\t\t\tpanel.loadUrl(type);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tsubpanel.initParams = panel.initParams;\r\n");
      out.write("\t\t\tpanel.loadUrl(type);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tpanel.add(subpanel);\r\n");
      out.write("\tpanel.doLayout();\r\n");
      out.write("\t// 初始化视图数据\r\n");
      out.write("\tpanel.refresh(panel.initParams);\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
