/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2013-01-28 08:43:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.app.mkoa.mail;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mail_signature_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	String panelid = request.getParameter("panelid");

      out.write("\n");
      out.write("<script language='javascript'>\n");
      out.write("Ext.onReady(function(){\n");
      out.write("\n");
      out.write("\tvar panel = Ext.getCmp('");
      out.print(panelid);
      out.write("');\n");
      out.write("\n");
      out.write("\t// 保存按钮\n");
      out.write("\tvar btnSave = new Ext.Action({\n");
      out.write("\t\ttext : '保存',\n");
      out.write("\t\ticonCls : 'icon-sys-save',\n");
      out.write("\t\thandler : function(){\n");
      out.write("\t\t\tvar useflag = 0;\n");
      out.write("\t\t\tif (form.getForm().findField(\"F_USE_FLAG\").getValue() == true) {\n");
      out.write("\t\t\t\tuseflag = 1;\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tAppMailDirect.saveSignature(useflag, form.getForm().findField(\"F_SIGNATURE\").getValue(), function(result, event) {\n");
      out.write("\t\t\t\tif (result.success) {\n");
      out.write("\t\t\t\t\tExt.Msg.alert('信息提示', '签名设置完毕！');\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tExt.Msg.alert('信息提示', '签名设置失败！');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\tvar buttons = ['->',btnSave];\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\tvar form = new Ext.form.FormPanel({\n");
      out.write("\t\tautoScroll : true,\n");
      out.write("\t\tlayout:'form',\n");
      out.write("\t\tborder : false,\n");
      out.write("\t\ttbar : buttons,\n");
      out.write("\t\ttrackResetOnLoad : true,\n");
      out.write("\t\tlabelWidth: 40,\n");
      out.write("\t\tfileUpload : true,\n");
      out.write("\t\tbodyStyle : \"padding:10px;padding-left:30px;padding-right:30px;\",\n");
      out.write("\t\tapi : {\n");
      out.write("\t\t\tload : AppMailDirect.loadSignature\n");
      out.write("\t\t},\n");
      out.write("\t\titems : [{\n");
      out.write("\t\t\txtype: 'checkbox',\n");
      out.write("\t\t\tname: 'F_USE_FLAG',\n");
      out.write("\t\t\tfieldLabel: '启用',\n");
      out.write("\t\t\tinputValue: 1,\n");
      out.write("\t\t\tuncheckedValue: 0\n");
      out.write("\t\t}, {\n");
      out.write("\t\t\txtype: 'htmleditor',\n");
      out.write("\t\t\tanchor: '100%',\n");
      out.write("\t\t\tname: 'F_SIGNATURE',\n");
      out.write("\t\t\tfieldLabel: '签名',\n");
      out.write("\t\t\tfontFamilies : [\n");
      out.write("                'Sans-Serif',\n");
      out.write("                'Serif',\n");
      out.write("                'Arial Black',\n");
      out.write("                'Arial Narrow',\n");
      out.write("                'Comic Sans MS',\n");
      out.write("                'Courier New',\n");
      out.write("                'Garamond',\n");
      out.write("                'Georgia',\n");
      out.write("                'Tahoma',\n");
      out.write("                'Times New Roman',\n");
      out.write("                'Trebuchet MS',\n");
      out.write("                'Verdana'\n");
      out.write("            ],\n");
      out.write("\t\t\theight:200\n");
      out.write("\t\t}]\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t// 视图刷新\n");
      out.write("\tpanel.refresh = function(){\n");
      out.write("\t\tform.getForm().load();\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\t// 输出附加脚本 end\n");
      out.write("\tpanel.add(form);\n");
      out.write("\tpanel.doLayout();\n");
      out.write("\t// 初始化视图数据\n");
      out.write("\tpanel.refresh();\n");
      out.write("});\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
