Ext.ux.Portlet=Ext.extend(Ext.Panel,{anchor:"100%",frame:true,collapsible:true,draggable:true,cls:"x-portlet",listeners:{afterrender:function(){var a=this.getEl().id,b=this.getEl().getHeight(),c=this;this.resizeWrap=new Ext.Resizable(a,{handles:"s",height:b,minHeight:50,dynamic:true,listeners:{resize:function(d,e,f){c.setHeight(f);MixkyApp.getSubject(c.key).webheight=f}}})},beforedestroy:function(){delete this.resizeWrap}}});Ext.reg("portlet",Ext.ux.Portlet);Ext.ux.PortalColumn=Ext.extend(Ext.Container,{layout:"anchor",defaultType:"portlet",cls:"x-portal-column"});Ext.reg("portalcolumn",Ext.ux.PortalColumn);Ext.ns("Ext.ux");Ext.ux.Portal=Ext.extend(Ext.Panel,{layout:"column",autoScroll:true,cls:"x-portal",defaultType:"portalcolumn",initComponent:function(){Ext.ux.Portal.superclass.initComponent.call(this);this.addEvents({validatedrop:true,beforedragover:true,dragover:true,beforedrop:true,drop:true})},initEvents:function(){Ext.ux.Portal.superclass.initEvents.call(this);this.dd=new Ext.ux.Portal.DropZone(this,this.dropConfig)},beforeDestroy:function(){this.dd&&this.dd.unreg();Ext.ux.Portal.superclass.beforeDestroy.call(this)}});
Ext.reg("portal",Ext.ux.Portal);Ext.ux.Portal.DropZone=function(a,b){this.portal=a;Ext.dd.ScrollManager.register(a.body);Ext.ux.Portal.DropZone.superclass.constructor.call(this,a.bwrap.dom,b);a.body.ddScrollConfig=this.ddScrollConfig};
Ext.extend(Ext.ux.Portal.DropZone,Ext.dd.DropTarget,{ddScrollConfig:{vthresh:50,hthresh:-1,animate:true,increment:200},createEvent:function(a,b,c,d,e,f){return{portal:this.portal,panel:c.panel,columnIndex:d,column:e,position:f,data:c,source:a,rawEvent:b,status:this.dropAllowed}},notifyOver:function(a,b,c){var d=b.getXY(),e=this.portal,f=a.proxy;if(!this.grid)this.grid=this.getGrid();var h=e.body.dom.clientWidth;if(this.lastCW){if(this.lastCW!=h){this.lastCW=h;e.doLayout();this.grid=this.getGrid()}}else this.lastCW=
h;h=0;for(var i=this.grid.columnX,g=false,l=i.length;h<l;h++)if(d[0]<i[h].x+i[h].w){g=true;break}g||h--;var k;i=false;g=0;var j=e.items.itemAt(h),o=j.items.items,n=false;for(l=o.length;g<l;g++){k=o[g];var r=k.el.getHeight();if(r===0)n=true;else if(k.el.getY()+r/2>d[1]){i=true;break}}g=(i&&k?g:j.items.getCount())+(n?-1:0);a=this.createEvent(a,b,c,h,j,g);if(e.fireEvent("validatedrop",a)!==false&&e.fireEvent("beforedragover",a)!==false){f.getProxy().setWidth("auto");k?f.moveProxy(k.el.dom.parentNode,
i?k.el.dom:null):f.moveProxy(j.el.dom,null);this.lastPos={c:j,col:h,p:n||i&&k?g:false};this.scrollPos=e.body.getScroll();e.fireEvent("dragover",a)}return a.status},notifyOut:function(){delete this.grid},notifyDrop:function(a,b,c){delete this.grid;if(this.lastPos){var d=this.lastPos.c,e=this.lastPos.p;b=this.createEvent(a,b,c,this.lastPos.col,d,e!==false?e:d.items.getCount());if(this.portal.fireEvent("validatedrop",b)!==false&&this.portal.fireEvent("beforedrop",b)!==false){a.proxy.getProxy().remove();
a.panel.el.dom.parentNode.removeChild(a.panel.el.dom);if(e!==false){d==a.panel.ownerCt&&d.items.items.indexOf(a.panel)<=e&&e++;d.insert(e,a.panel)}else d.add(a.panel);d.doLayout();this.portal.fireEvent("drop",b);var f=this.scrollPos.top;if(f){var h=this.portal.body.dom;setTimeout(function(){h.scrollTop=f},10)}}delete this.lastPos}},getGrid:function(){var a=this.portal.bwrap.getBox();a.columnX=[];this.portal.items.each(function(b){a.columnX.push({x:b.el.getX(),w:b.el.getWidth()})});return a},unreg:function(){Ext.ux.Portal.DropZone.superclass.unreg.call(this)}});Ext.ns("Ext.ux.grid");
Ext.ux.grid.RowEditor=Ext.extend(Ext.Panel,{floating:true,shadow:false,layout:"hbox",cls:"x-small-editor",buttonAlign:"center",baseCls:"x-row-editor",elements:"header,footer,body",frameWidth:5,buttonPad:3,clicksToEdit:"auto",monitorValid:true,focusDelay:250,errorSummary:true,saveText:"Save",cancelText:"Cancel",commitChangesText:"You need to commit or cancel your changes",errorText:"Errors",defaults:{normalWidth:true},initComponent:function(){Ext.ux.grid.RowEditor.superclass.initComponent.call(this);this.addEvents("beforeedit",
"canceledit","validateedit","afteredit","beforefieldsetvalue")},init:function(a){this.ownerCt=this.grid=a;if(this.clicksToEdit===2)a.on("rowdblclick",this.onRowDblClick,this);else{a.on("rowclick",this.onRowClick,this);Ext.isIE&&a.on("rowdblclick",this.onRowDblClick,this)}a.getStore().on("remove",function(){this.stopEditing(false)},this);a.on({scope:this,keydown:this.onGridKey,columnresize:this.verifyLayout,columnmove:this.refreshFields,reconfigure:this.refreshFields,beforedestroy:this.beforedestroy,
destroy:this.destroy,bodyscroll:{buffer:250,fn:this.positionButtons}});a.getColumnModel().on("hiddenchange",this.verifyLayout,this,{delay:1});a.getView().on("refresh",this.stopEditing.createDelegate(this,[]))},beforedestroy:function(){this.grid.getStore().un("remove",this.onStoreRemove,this);this.stopEditing(false);Ext.destroy(this.btns)},refreshFields:function(){this.initFields();this.verifyLayout()},isDirty:function(){var a;this.items.each(function(b){if(String(this.values[b.id])!==String(b.getValue())){a=
true;return false}},this);return a},startEditing:function(a,b){if(this.editing&&this.isDirty())this.showTooltip(this.commitChangesText);else{if(Ext.isObject(a))a=this.grid.getStore().indexOf(a);if(this.fireEvent("beforeedit",this,a)!==false){this.editing=true;var c=this.grid,d=c.getView(),e=d.getRow(a),f=c.store.getAt(a);this.record=f;this.rowIndex=a;this.values={};this.rendered||this.render(d.getEditorParent());this.setSize(Ext.fly(e).getWidth());this.initialized||this.initFields();a=c.getColumnModel();
d=this.items.items;for(var h,i,g=0,l=a.getColumnCount();g<l;g++){i=this.preEditValue(f,a.getDataIndex(g));h=d[g];this.fireEvent("beforefieldsetvalue",h,i,f,c,e,g)!==false&&h.setValue(i);this.values[h.id]=i===0?0:i||""}this.verifyLayout(true);this.isVisible()?this.el.setXY(Ext.fly(e).getXY(),{duration:0.15}):this.setPagePosition(Ext.fly(e).getXY());this.isVisible()||this.show().doLayout();b!==false&&this.doFocus.defer(this.focusDelay,this)}}},stopEditing:function(a){this.editing=false;if(this.isVisible())if(a===
false||!this.isValid()){this.hide();this.fireEvent("canceledit",this,a===false)}else{a={};for(var b=this.record,c=false,d=this.grid.colModel,e=this.items.items,f=0,h=d.getColumnCount();f<h;f++)if(!d.isHidden(f)){var i=d.getDataIndex(f);if(!Ext.isEmpty(i)){var g=b.data[i],l=this.postEditValue(e[f].getValue(),g,b,i);if(String(g)!==String(l)){a[i]=l;c=true}}}if(c&&this.fireEvent("validateedit",this,a,b,this.rowIndex)!==false){b.beginEdit();Ext.iterate(a,function(k,j){b.set(k,j)});b.endEdit();this.fireEvent("afteredit",
this,a,b,this.rowIndex)}this.hide()}},verifyLayout:function(a){if(this.el&&(this.isVisible()||a===true)){a=this.grid.getView().getRow(this.rowIndex);this.setSize(Ext.fly(a).getWidth(),Ext.isIE?Ext.fly(a).getHeight()+9:undefined);a=this.grid.colModel;for(var b=this.items.items,c=0,d=a.getColumnCount();c<d;c++)if(a.isHidden(c))b[c].hide();else{var e=0;e+=c===d-1?3:1;b[c].show();b[c].setWidth(a.getColumnWidth(c)-e)}this.doLayout();this.positionButtons()}},slideHide:function(){this.hide()},initFields:function(){var a=
this.grid.getColumnModel(),b=Ext.layout.ContainerLayout.prototype.parseMargins;this.removeAll(false);for(var c=0,d=a.getColumnCount();c<d;c++){var e=a.getColumnAt(c),f=e.getEditor();f=f?f.field:e.displayEditor||new Ext.form.DisplayField;f.margins=c==0?b("0 1 2 1"):c==d-1?b("0 0 2 1"):b("0 1 2");f.setWidth(a.getColumnWidth(c));f.column=e;if(f.ownerCt!==this){f.on("focus",this.ensureVisible,this);f.on("specialkey",this.onKey,this)}this.insert(c,f)}this.initialized=true},onKey:function(a,b){if(b.getKey()===
b.ENTER){this.stopEditing(true);b.stopPropagation()}},onGridKey:function(a){if(a.getKey()===a.ENTER&&!this.isVisible()){var b=this.grid.getSelectionModel().getSelected();if(b){this.startEditing(this.grid.store.indexOf(b));a.stopPropagation()}}},ensureVisible:function(a){this.isVisible()&&this.grid.getView().ensureVisible(this.rowIndex,this.grid.colModel.getIndexById(a.column.id),true)},onRowClick:function(a,b,c){if(this.clicksToEdit=="auto"){a=this.lastClickIndex;this.lastClickIndex=b;if(a!=b&&!this.isVisible())return}this.startEditing(b,
false);this.doFocus.defer(this.focusDelay,this,[c.getPoint()])},onRowDblClick:function(a,b,c){this.startEditing(b,false);this.doFocus.defer(this.focusDelay,this,[c.getPoint()])},onRender:function(){Ext.ux.grid.RowEditor.superclass.onRender.apply(this,arguments);this.el.swallowEvent(["keydown","keyup","keypress"]);this.btns=new Ext.Panel({baseCls:"x-plain",cls:"x-btns",elements:"body",layout:"table",width:this.minButtonWidth*2+this.frameWidth*2+this.buttonPad*4,items:[{ref:"saveBtn",itemId:"saveBtn",
xtype:"button",text:this.saveText,width:this.minButtonWidth,handler:this.stopEditing.createDelegate(this,[true])},{xtype:"button",text:this.cancelText,width:this.minButtonWidth,handler:this.stopEditing.createDelegate(this,[false])}]});this.btns.render(this.bwrap)},afterRender:function(){Ext.ux.grid.RowEditor.superclass.afterRender.apply(this,arguments);this.positionButtons();this.monitorValid&&this.startMonitoring()},onShow:function(){this.monitorValid&&this.startMonitoring();Ext.ux.grid.RowEditor.superclass.onShow.apply(this,
arguments)},onHide:function(){Ext.ux.grid.RowEditor.superclass.onHide.apply(this,arguments);this.stopMonitoring();this.grid.getView().focusRow(this.rowIndex)},positionButtons:function(){if(this.btns){var a=this.grid,b=this.el.dom.clientHeight,c=a.getView().scroller.dom.scrollLeft,d=this.btns.getWidth();this.btns.el.shift({left:Math.min(a.getWidth(),a.getColumnModel().getTotalWidth())/2-d/2+c,top:b-2,stopFx:true,duration:0.2})}},preEditValue:function(a,b){a=a.data[b];return this.autoEncode&&typeof a===
"string"?Ext.util.Format.htmlDecode(a):a},postEditValue:function(a){return this.autoEncode&&typeof a=="string"?Ext.util.Format.htmlEncode(a):a},doFocus:function(a){if(this.isVisible()){var b=0,c=this.grid.getColumnModel();if(a)b=this.getTargetColumnIndex(a);for(var d=b||0,e=c.getColumnCount();d<e;d++){a=c.getColumnAt(d);b=a.getEditor();if(!a.hidden&&b){b.field.focus();break}}}},getTargetColumnIndex:function(a){var b=this.grid,c=b.view;a=a.left;b=b.colModel.config;for(var d=0,e=false,f;f=b[d];d++)if(!f.hidden)if(Ext.fly(c.getHeaderCell(d)).getRegion().right>=
a){e=d;break}return e},startMonitoring:function(){if(!this.bound&&this.monitorValid){this.bound=true;Ext.TaskMgr.start({run:this.bindHandler,interval:this.monitorPoll||200,scope:this})}},stopMonitoring:function(){this.bound=false;this.tooltip&&this.tooltip.hide()},isValid:function(){var a=true;this.items.each(function(b){if(!b.isValid(true))return a=false});return a},bindHandler:function(){if(!this.bound)return false;var a=this.isValid();!a&&this.errorSummary&&this.showTooltip(this.getErrorText().join(""));
this.btns.saveBtn.setDisabled(!a);this.fireEvent("validation",this,a)},showTooltip:function(a){var b=this.tooltip;if(!b)b=this.tooltip=new Ext.ToolTip({maxWidth:600,cls:"errorTip",width:300,title:this.errorText,autoHide:false,anchor:"left",anchorToTarget:true,mouseOffset:[40,0]});var c=this.grid.getView(),d=parseInt(this.el.dom.style.top,10);c=c.scroller.dom.scrollTop;var e=this.el.getHeight();if(d+e>=c){b.initTarget(this.items.last().getEl());if(!b.rendered){b.show();b.hide()}b.body.update(a);b.doAutoWidth(20);
b.show()}else b.rendered&&b.hide()},getErrorText:function(){var a=["<ul>"];this.items.each(function(b){b.isValid(true)||a.push("<li>",b.getActiveError(),"</li>")});a.push("</ul>");return a}});Ext.preg("roweditor",Ext.ux.grid.RowEditor);Ext.namespace("Ext.ux.form");
Ext.ux.form.HexField=Ext.extend(Ext.form.TextField,{initEvents:function(){Ext.ux.form.HexField.superclass.initEvents.call(this);this.el.on("keypress",function(a){var b=a.getKey();if(!(!Ext.isIE&&(a.isSpecialKey()||b==a.BACKSPACE||b==a.DELETE))){b=(new Ext.ux.form.HexField.Selection(document.getElementById(this.id))).create();b=b.end-b.start;var c=a.getCharCode();c=String.fromCharCode(c);var d=c+this.getValue();if("0123456789abcdefABCDEF".indexOf(c)===-1||d.length>6&&b===0)a.stopEvent()}},this)},validateValue:function(a){if(!Ext.ux.form.HexField.superclass.validateValue.call(this,
a))return false;if(!/^[0-9a-fA-F]{6}$/.test(a))return false;return true}});Ext.reg("hexfield",Ext.ux.form.HexField);Ext.ux.form.HexField.Selection=function(a){this.element=a};Ext.ux.form.HexField.Selection.prototype.create=function(){return document.selection!=null&&this.element.selectionStart==null?this._ieGetSelection():this._mozillaGetSelection()};Ext.ux.form.HexField.Selection.prototype._mozillaGetSelection=function(){return{start:this.element.selectionStart,end:this.element.selectionEnd}};
Ext.ux.form.HexField.Selection.prototype._ieGetSelection=function(){this.element.focus();for(var a=document.selection.createRange(),b=a.getBookmark(),c=this.element.value,d=c,e=this._createSelectionMarker();c.indexOf(e)!=-1;)e=this._createSelectionMarker();c=a.parentElement();if(c==null||c.type!="text")return{start:0,end:0};a.text=e+a.text+e;c=this.element.value;var f={};f.start=c.indexOf(e);c=c.replace(e,"");f.end=c.indexOf(e);this.element.value=d;a.moveToBookmark(b);a.select();return f};
Ext.ux.form.HexField.Selection.prototype._createSelectionMarker=function(){return"##SELECTION_MARKER_"+Math.random()+"##"};/*
: LGPLv3
: BSD
*/
Ext.namespace("Ext.ux","Ext.ux.menu");
Ext.ux.ColorPicker=Ext.extend(Ext.BoxComponent,{showWebSafeColorbox:false,showInverseColorbox:false,showColorbox:true,initComponent:function(){this.applyDefaultsCP();Ext.ux.ColorPicker.superclass.initComponent.apply(this,arguments);this.addEvents("select")},onRender:function(){Ext.ux.ColorPicker.superclass.onRender.apply(this,arguments);this.body=this.body||this.container||this.renderTo||Ext.DomHelper.append(Ext.getBody(),{},true);if(!this.el){this.el=this.body;this.cls&&Ext.get(this.el).addClass(this.cls)}this.renderComponent()},
applyDefaultsCP:function(){Ext.apply(this,{cls:"x-cp-mainpanel",resizable:this.resizable||false,HSV:{h:0,s:0,v:0},updateMode:null})},renderComponent:function(){Ext.DomHelper.append(this.body,{id:this.cpGetId("rgb"),cls:"x-cp-rgbpicker"});Ext.DomHelper.append(this.body,{id:this.cpGetId("hue"),cls:"x-cp-huepicker"});this.huePicker=Ext.DomHelper.append(this.body,{cls:"x-cp-hueslider"});this.hueDD=new Ext.dd.DD(this.huePicker,"huePicker");this.hueDD.constrainTo(this.cpGetId("hue"),{top:-7,right:-3,bottom:-7,
left:-3});this.hueDD.onDrag=this.moveHuePicker.createDelegate(this);Ext.get(this.cpGetId("hue")).on("mousedown",this.clickHUEPicker.createDelegate(this));Ext.get(this.huePicker).moveTo(Ext.get(this.cpGetId("hue")).getLeft()-3,Ext.get(this.cpGetId("hue")).getTop()-7);this.rgbPicker=Ext.DomHelper.append(this.body,{cls:"x-cp-rgbslider"});this.rgbDD=new Ext.dd.DD(this.rgbPicker,"rgbPicker");this.rgbDD.constrainTo(this.cpGetId("rgb"),-7);this.rgbDD.onDrag=this.moveRGBPicker.createDelegate(this);Ext.get(this.cpGetId("rgb")).on("mousedown",
this.clickRGBPicker.createDelegate(this));Ext.get(this.rgbPicker).moveTo(Ext.get(this.cpGetId("rgb")).getLeft()-7,Ext.get(this.cpGetId("rgb")).getTop()-7);this.formPanel=new Ext.form.FormPanel({border:false,renderTo:Ext.DomHelper.append(this.body,{id:this.cpGetId("fCont"),cls:"x-cp-formcontainer"},true),frame:false,labelAlign:"left",labelWidth:10,forceLayout:true,items:[{border:false,layout:"form",id:this.cpGetId("cCont")},{bodyStyle:"padding-top:10px;",border:false,layout:"column",items:[{border:false,
columnWidth:0.5,layout:"form",defaultType:"numberfield",defaults:{width:30,value:0,minValue:0,maxValue:255,allowBlank:false,labelSeparator:"",enableKeyEvents:true},items:[{fieldLabel:"R",id:this.cpGetId("iRed")},{fieldLabel:"G",id:this.cpGetId("iGreen")},{fieldLabel:"B",id:this.cpGetId("iBlue")}]},{border:false,columnWidth:0.5,layout:"form",defaultType:"numberfield",defaults:{width:30,value:0,minValue:0,maxValue:255,allowBlank:false,labelSeparator:"",enableKeyEvents:true},items:[{fieldLabel:"H",maxValue:360,
id:this.cpGetId("iHue")},{fieldLabel:"S",id:this.cpGetId("iSat")},{fieldLabel:"V",id:this.cpGetId("iVal")}]},{border:false,layout:"form",labelAlign:"left",items:[{width:88,value:"000000",labelSeparator:"",allowBlank:false,fieldLabel:"#",id:this.cpGetId("iHexa"),value:"000000",xtype:"hexfield",enableKeyEvents:true}]}]}]});Ext.getCmp(this.cpGetId("iRed")).on("keyup",this.updateFromIRGB.createDelegate(this),{buffer:750});Ext.getCmp(this.cpGetId("iGreen")).on("keyup",this.updateFromIRGB.createDelegate(this),
{buffer:750});Ext.getCmp(this.cpGetId("iBlue")).on("keyup",this.updateFromIRGB.createDelegate(this),{buffer:750});Ext.getCmp(this.cpGetId("iHue")).on("keyup",this.updateFromIHSV.createDelegate(this),{buffer:750});Ext.getCmp(this.cpGetId("iSat")).on("keyup",this.updateFromIHSV.createDelegate(this),{buffer:750});Ext.getCmp(this.cpGetId("iVal")).on("keyup",this.updateFromIHSV.createDelegate(this),{buffer:750});Ext.getCmp(this.cpGetId("iHexa")).on("keyup",this.updateFromIHexa.createDelegate(this),{buffer:750});
var a=Ext.getCmp(this.cpGetId("cCont")).body;if(this.showWebSafeColorbox===true){Ext.DomHelper.append(a,{cls:"x-cp-colorbox",id:this.cpGetId("cWebSafe")},true).update("Websafe");Ext.get(this.cpGetId("cWebSafe")).on("click",this.updateFromBox.createDelegate(this))}if(this.showInverseColorbox===true){Ext.DomHelper.append(a,{cls:"x-cp-colorbox",id:this.cpGetId("cInverse")},true).update("Inverse");Ext.get(this.cpGetId("cInverse")).on("click",this.updateFromBox.createDelegate(this))}if(this.showColorbox===
true){Ext.DomHelper.append(a,{cls:"x-cp-colorbox",id:this.cpGetId("cColor")},true);Ext.get(this.cpGetId("cColor")).on("click",this.selectColor.createDelegate(this))}Ext.DomHelper.append(this.body,{tag:"br",cls:"x-cp-clearfloat"})},cpGetId:function(a){return this.getId()+"__"+(a||"cp")},updateRGBPosition:function(a,b){this.updateMode="click";a=a<0?0:a;a=a>181?181:a;b=b<0?0:b;b=b>181?181:b;this.HSV.s=this.getSaturation(a);this.HSV.v=this.getValue(b);Ext.get(this.rgbPicker).moveTo(Ext.get(this.cpGetId("rgb")).getLeft()+
a-7,Ext.get(this.cpGetId("rgb")).getTop()+b-7,this.animateMove||true);this.updateColor()},updateHUEPosition:function(a){this.updateMode="click";a=a<1?1:a;a=a>181?181:a;this.HSV.h=Math.round(360/181*(181-a));Ext.get(this.huePicker).moveTo(Ext.get(this.huePicker).getLeft(),Ext.get(this.cpGetId("hue")).getTop()+a-7,this.animateMove||true);this.updateRGBPicker(this.HSV.h);this.updateColor()},clickRGBPicker:function(a){this.updateRGBPosition(a.xy[0]-Ext.get(this.cpGetId("rgb")).getLeft(),a.xy[1]-Ext.get(this.cpGetId("rgb")).getTop())},
clickHUEPicker:function(a){this.updateHUEPosition(a.xy[1]-Ext.get(this.cpGetId("hue")).getTop())},moveRGBPicker:function(){this.rgbDD.constrainTo(this.cpGetId("rgb"),-7);this.updateRGBPosition(Ext.get(this.rgbPicker).getLeft()-Ext.get(this.cpGetId("rgb")).getLeft()+7,Ext.get(this.rgbPicker).getTop()-Ext.get(this.cpGetId("rgb")).getTop()+7)},moveHuePicker:function(){this.hueDD.constrainTo(this.cpGetId("hue"),{top:-7,right:-3,bottom:-7,left:-3});this.updateHUEPosition(Ext.get(this.huePicker).getTop()-
Ext.get(this.cpGetId("hue")).getTop()+7)},updateRGBPicker:function(a){this.updateMode="click";Ext.get(this.cpGetId("rgb")).setStyle({"background-color":"#"+this.rgbToHex(this.hsvToRgb(a,1,1))});this.updateColor()},updateColor:function(){var a=this.hsvToRgb(this.HSV.h,this.HSV.s,this.HSV.v),b=this.websafe(a),c=this.invert(a),d=this.invert(b);this.updateMode!=="hexa"&&Ext.getCmp(this.cpGetId("iHexa")).setValue(this.rgbToHex(a));if(this.updateMode!=="rgb"){Ext.getCmp(this.cpGetId("iRed")).setValue(a[0]);
Ext.getCmp(this.cpGetId("iGreen")).setValue(a[1]);Ext.getCmp(this.cpGetId("iBlue")).setValue(a[2])}if(this.updateMode!=="hsv"){Ext.getCmp(this.cpGetId("iHue")).setValue(Math.round(this.HSV.h));Ext.getCmp(this.cpGetId("iSat")).setValue(Math.round(this.HSV.s*100));Ext.getCmp(this.cpGetId("iVal")).setValue(Math.round(this.HSV.v*100))}this.showColorbox===true&&Ext.get(this.cpGetId("cColor")).setStyle({background:"#"+this.rgbToHex(a),color:"#"+this.rgbToHex(c)});this.showInverseColorbox===true&&Ext.get(this.cpGetId("cInverse")).setStyle({background:"#"+
this.rgbToHex(c),color:"#"+this.rgbToHex(a)});this.showWebSafeColorbox===true&&Ext.get(this.cpGetId("cWebSafe")).setStyle({background:"#"+this.rgbToHex(b),color:"#"+this.rgbToHex(d)});if(this.updateMode!=="click"){Ext.get(this.huePicker).moveTo(Ext.get(this.huePicker).getLeft(),Ext.get(this.cpGetId("hue")).getTop()+this.getHPos(Ext.getCmp(this.cpGetId("iHue")).getValue())-7,this.animateMove||true);Ext.get(this.rgbPicker).moveTo(Ext.get(this.cpGetId("rgb")).getLeft()+this.getSPos(Ext.getCmp(this.cpGetId("iSat")).getValue()/
100)-7,Ext.get(this.cpGetId("hue")).getTop()+this.getVPos(Ext.getCmp(this.cpGetId("iVal")).getValue()/100)-7,this.animateMove||true)}Ext.get(this.cpGetId("rgb")).setStyle({"background-color":"#"+this.rgbToHex(this.hsvToRgb(Ext.getCmp(this.cpGetId("iHue")).getValue(),1,1))});this.selectColor()},setColor:function(a){if(/^[0-9a-fA-F]{6}$/.test(a)){Ext.getCmp(this.cpGetId("iHexa")).setValue(a);this.updateFromIHexa()}},getColor:function(){return Ext.getCmp(this.cpGetId("iHexa")).getValue()},updateFromIRGB:function(){this.updateMode=
"rgb";var a=this.rgbToHsv(Ext.getCmp(this.cpGetId("iRed")).getValue(),Ext.getCmp(this.cpGetId("iGreen")).getValue(),Ext.getCmp(this.cpGetId("iBlue")).getValue());this.HSV={h:a[0],s:a[1],v:a[2]};this.updateColor()},updateFromIHSV:function(){this.updateMode="hsv";this.HSV={h:Ext.getCmp(this.cpGetId("iHue")).getValue(),s:Ext.getCmp(this.cpGetId("iSat")).getValue()/100,v:Ext.getCmp(this.cpGetId("iVal")).getValue()/100};this.updateColor()},updateFromIHexa:function(){var a=Ext.getCmp(this.cpGetId("iHexa")).getValue();
if(/^[0-9a-fA-F]{6}$/.test(a)){this.updateMode="hexa";a=this.rgbToHsv(this.hexToRgb(a));this.HSV={h:a[0],s:a[1],v:a[2]};this.updateColor()}},updateFromBox:function(a,b){this.updateMode="click";a=this.rgbToHsv(this.hexToRgb(Ext.get(b).getColor("backgroundColor","","")));this.HSV={h:a[0],s:a[1],v:a[2]};this.updateColor()},selectColor:function(){this.fireEvent("select",this,this.getColor())},hsvToRgb:function(a,b,c){if(a instanceof Array)return this.hsvToRgb.call(this,a[0],a[1],a[2]);var d,e,f,h,i,g;
h=Math.floor(a/60%6);i=a/60-h;a=c*(1-b);g=c*(1-i*b);b=c*(1-(1-i)*b);switch(h){case 0:d=c;e=b;f=a;break;case 1:d=g;e=c;f=a;break;case 2:d=a;e=c;f=b;break;case 3:d=a;e=g;f=c;break;case 4:d=b;e=a;f=c;break;case 5:d=c;e=a;f=g;break}return[this.realToDec(d),this.realToDec(e),this.realToDec(f)]},rgbToHsv:function(a,b,c){if(a instanceof Array)return this.rgbToHsv.call(this,a[0],a[1],a[2]);a/=255;b/=255;c/=255;var d,e,f,h;d=Math.min(Math.min(a,b),c);e=Math.max(Math.max(a,b),c);f=e-d;switch(e){case d:h=0;
break;case a:h=60*(b-c)/f;if(b<c)h+=360;break;case b:h=60*(c-a)/f+120;break;case c:h=60*(a-b)/f+240;break}a=e===0?0:1-d/e;return[Math.round(h),a,e]},realToDec:function(a){return Math.min(255,Math.round(a*256))},rgbToHex:function(a,b,c){if(a instanceof Array)return this.rgbToHex.call(this,a[0],a[1],a[2]);return this.decToHex(a)+this.decToHex(b)+this.decToHex(c)},decToHex:function(a){a=parseInt(a,10);a=!isNaN(a)?a:0;a=a>255||a<0?0:a;return"0123456789ABCDEF".charAt((a-a%16)/16)+"0123456789ABCDEF".charAt(a%
16)},getHCharPos:function(a){return"0123456789ABCDEF".indexOf(a.toUpperCase())},hexToDec:function(a){a=a.split("");return this.getHCharPos(a[0])*16+this.getHCharPos(a[1])},hexToRgb:function(a){return[this.hexToDec(a.substr(0,2)),this.hexToDec(a.substr(2,2)),this.hexToDec(a.substr(4,2))]},getHue:function(a){a=360-Math.round((181-a)/181*360);return a===360?0:a},getHPos:function(a){return 181-a*(181/360)},getSaturation:function(a){return a/181},getSPos:function(a){return a*181},getValue:function(a){return(181-
a)/181},getVPos:function(a){return 181-a*181},checkSafeNumber:function(a){if(!isNaN(a)){a=Math.min(Math.max(0,a),255);var b,c;for(b=0;b<256;b+=51){c=b+51;if(a>=b&&a<=c)return a-b>25?c:b}}return a},websafe:function(a,b,c){if(a instanceof Array)return this.websafe.call(this,a[0],a[1],a[2]);return[this.checkSafeNumber(a),this.checkSafeNumber(b),this.checkSafeNumber(c)]},invert:function(a,b,c){if(a instanceof Array)return this.invert.call(this,a[0],a[1],a[2]);return[255-a,255-b,255-c]}});
Ext.ux.ColorDialog=Ext.extend(Ext.Window,{constructor:function(a){a=a||{};Ext.applyIf(a,{buttons:[{handler:this.onOk,scope:this,text:"Ok"},{handler:this[this.closeAction].createDelegate(this,[]),scope:this,text:"Cancel"}]});Ext.ux.ColorDialog.superclass.constructor.apply(this,[a])},initComponent:function(){this.width=!this.width||this.width<353?353:this.width;this.applyDefaultsCP();Ext.ux.ColorDialog.superclass.initComponent.apply(this,arguments)},onRender:function(){Ext.ux.ColorDialog.superclass.onRender.apply(this,
arguments);this.renderComponent()},onOk:function(){this.callback&&this.scope&&this.callback.call(this.scope,this.getColor());this[this.closeAction]()},show:function(a,b,c){this.rendered||this.render(Ext.getBody());if(this.hidden===false)this.toFront();else if(this.fireEvent("beforeshow",this)!==false){if(b)this.callback=b;if(c)this.scope=c;this.hidden=false;this.beforeShow();this.afterShow();a=a||"000000";this.setColor(a)}}});Ext.applyIf(Ext.ux.ColorDialog.prototype,Ext.ux.ColorPicker.prototype);
Ext.ux.ColorPanel=Ext.extend(Ext.Panel,{initComponent:function(){this.width=!this.width||this.width<300?300:this.width;this.applyDefaultsCP();Ext.ux.ColorPanel.superclass.initComponent.apply(this,arguments)},onRender:function(){Ext.ux.ColorPanel.superclass.onRender.apply(this,arguments);this.renderComponent()}});Ext.applyIf(Ext.ux.ColorPanel.prototype,Ext.ux.ColorPicker.prototype);Ext.reg("colorpicker",Ext.ux.ColorPicker);Ext.reg("colordialog",Ext.ux.ColorDialog);Ext.reg("colorpanel",Ext.ux.ColorPanel);
Ext.ux.menu.ColorItem=function(a){a||(a={});a.style="width:350px;";Ext.ux.menu.ColorItem.superclass.constructor.call(this,new Ext.ux.ColorPicker(a),a);this.picker=this.component;this.addEvents("select");this.picker.on("render",function(b){b.getEl().swallowEvent("click")});this.picker.on("select",this.onSelect,this)};Ext.extend(Ext.ux.menu.ColorItem,Ext.menu.BaseItem,{onSelect:function(a,b){this.fireEvent("select",this,b,a);Ext.ux.menu.ColorItem.superclass.handleClick.call(this)}});
Ext.ux.menu.ColorMenu=function(a){Ext.ux.menu.ColorMenu.superclass.constructor.call(this,a);this.plain=true;a=new Ext.ux.menu.ColorItem(a);this.add(a);this.picker=a.picker;this.relayEvents(a,["select"])};Ext.extend(Ext.ux.menu.ColorMenu,Ext.menu.Menu,{beforeDestroy:function(){this.picker.destroy()}});Ext.ux.TabCloseMenu=function(){function a(e,f,h){c||(c=new Ext.menu.Menu({items:[{id:b.id+"-close",text:"\u5173\u95ed\u5f53\u524d\u6807\u7b7e",handler:function(){b.remove(d)}},{id:b.id+"-close-others",text:"\u5173\u95ed\u5176\u4ed6\u6807\u7b7e",handler:function(){b.items.each(function(g){g.closable&&g!=d&&b.remove(g)})}}]}));d=f;e=c.items;e.get(b.id+"-close").setDisabled(!f.closable);var i=true;b.items.each(function(){if(this!=f&&this.closable)return i=false});e.get(b.id+"-close-others").setDisabled(i);
h.stopEvent();c.showAt(h.getPoint())}var b,c,d;this.init=function(e){b=e;b.on("contextmenu",a)}};Ext.preg("tabclosemenu",Ext.ux.TabCloseMenu);Ext.ux.ProgressBarPager=Ext.extend(Object,{progBarWidth:225,defaultText:"Loading...",defaultAnimCfg:{duration:1,easing:"bounceOut"},constructor:function(a){a&&Ext.apply(this,a)},init:function(a){if(a.displayInfo){this.parent=a;a.items.indexOf(a.displayItem);a.remove(a.displayItem,true);this.progressBar=new Ext.ProgressBar({text:this.defaultText,width:this.progBarWidth,animate:this.defaultAnimCfg});a.displayItem=this.progressBar;a.add(a.displayItem);a.doLayout();Ext.apply(a,this.parentOverrides);this.progressBar.on("render",
function(b){b.el.applyStyles("cursor:pointer");b.el.on("click",this.handleProgressBarClick,this)},this);this.progressBar.on({scope:this,beforeDestroy:function(){this.progressBar.el.un("click",this.handleProgressBarClick,this)}})}},handleProgressBarClick:function(a){var b=this.parent,c=b.displayItem,d=this.progressBar.getBox();a=a.getXY()[0]-d.x;d=Math.ceil(b.store.getTotalCount()/b.pageSize);c=Math.ceil(a/(c.width/d));b.changePage(c)},parentOverrides:{updateInfo:function(){if(this.displayItem){var a=
this.store.getCount(),b=this.getPageData(),c=this.readPage(b);a=a==0?this.emptyMsg:String.format(this.displayMsg,this.cursor+1,this.cursor+a,this.store.getTotalCount());c=b.activePage;this.displayItem.updateProgress(c/b.pages,a,this.animate||this.defaultAnimConfig)}}}});Ext.preg("progressbarpager",Ext.ux.ProgressBarPager);Ext.ux.PanelResizer=Ext.extend(Ext.util.Observable,{minHeight:0,maxHeight:1E7,constructor:function(a){Ext.apply(this,a);this.events={};Ext.ux.PanelResizer.superclass.constructor.call(this,a)},init:function(a){this.panel=a;if(this.panel.elements.indexOf("footer")==-1)a.elements+=",footer";a.on("render",this.onRender,this)},onRender:function(a){this.handle=a.footer.createChild({cls:"x-panel-resize"});this.tracker=new Ext.dd.DragTracker({onStart:this.onDragStart.createDelegate(this),onDrag:this.onDrag.createDelegate(this),
onEnd:this.onDragEnd.createDelegate(this),tolerance:3,autoStart:300});this.tracker.initEl(this.handle);a.on("beforedestroy",this.tracker.destroy,this.tracker)},onDragStart:function(a){this.dragging=true;this.startHeight=this.panel.el.getHeight();this.fireEvent("dragstart",this,a)},onDrag:function(a){this.panel.setHeight((this.startHeight-this.tracker.getOffset()[1]).constrain(this.minHeight,this.maxHeight));this.fireEvent("drag",this,a)},onDragEnd:function(a){this.dragging=false;this.fireEvent("dragend",
this,a)}});Ext.preg("panelresizer",Ext.ux.PanelResizer);Ext.PagingRowNumberer=Ext.extend(Ext.grid.RowNumberer,{renderer:function(a,b,c,d,e,f){if(this.rowspan)b.cellAttr='rowspan="'+this.rowspan+'"';a=(a=f.lastOptions)?a.params:null;return(a&&a.start&&a.limit?a.start:0)+d+1}});Ext.DataView.LabelEditor=Ext.extend(Ext.Editor,{alignment:"tl-tl",hideEl:false,cls:"x-small-editor",shim:false,completeOnEnter:true,cancelOnEsc:true,labelSelector:"span.x-editable",constructor:function(a,b){Ext.DataView.LabelEditor.superclass.constructor.call(this,b||new Ext.form.TextField({allowBlank:false,growMin:90,growMax:240,grow:true,selectOnFocus:true}),a)},init:function(a){this.view=a;a.on("render",this.initEditor,this);this.on("complete",this.onSave,this)},initEditor:function(){this.view.on({scope:this,
containerclick:this.doBlur,click:this.doBlur});this.view.getEl().on("mousedown",this.onMouseDown,this,{delegate:this.labelSelector})},doBlur:function(){this.editing&&this.field.blur()},onMouseDown:function(a,b){if(!a.ctrlKey&&!a.shiftKey){var c=this.view.findItemFromChild(b);a.stopEvent();a=this.view.store.getAt(this.view.indexOf(c));this.startEdit(b,a.data[this.dataIndex]);this.activeRecord=a}else a.preventDefault()},onSave:function(a,b){this.activeRecord.set(this.dataIndex,b)}});
Ext.DataView.DragSelector=function(a){function b(){j=[];g.all.each(function(m){j[j.length]=m.getRegion()});o=g.el.getRegion()}function c(){return false}function d(m){return!r||m.target==g.el.dom}function e(){g.on("containerclick",c,g,{single:true});if(l)l.setDisplayed("block");else l=g.el.createChild({cls:"x-view-selector"});b();g.clearSelections()}function f(){var m=k.startXY,s=k.getXY(),p=Math.min(m[0],s[0]),t=Math.min(m[1],s[1]),q=Math.abs(m[0]-s[0]);m=Math.abs(m[1]-s[1]);n.left=p;n.top=t;n.right=
p+q;n.bottom=t+m;n.constrainTo(o);l.setRegion(n);p=0;for(t=j.length;p<t;p++){q=j[p];if((m=n.intersect(q))&&!q.selected){q.selected=true;g.select(p,true)}else if(!m&&q.selected){q.selected=false;g.deselect(p)}}}function h(){Ext.isIE||g.un("containerclick",c,g);l&&l.setDisplayed(false)}function i(m){k=new Ext.dd.DragTracker({onBeforeStart:d,onStart:e,onDrag:f,onEnd:h});k.initEl(m.el)}a=a||{};var g,l,k,j,o,n=new Ext.lib.Region(0,0,0,0),r=a.dragSafe===true;this.init=function(m){g=m;g.on("render",i)}};Ext.namespace("Cls","Cls.form","Cls.menu");
Cls.form.DateTimeField=Ext.extend(Ext.form.DateField,{timeFields:"auto",availableTimeFields:["H","h","G","g","i","s"],formatMap:{g:"h",G:"H"},timeFieldHandlers:null,initComponent:function(){Cls.form.DateTimeField.superclass.initComponent.call(this);if(!this.timeFields||this.timeFields=="auto"){this.timeFields="";for(d in this.availableTimeFields){var a=this.availableTimeFields[d];if(this.format.indexOf(a)>=0)this.timeFields+=a}}for(var b=[{tag:"img",src:Ext.BLANK_IMAGE_URL,cls:"x-form-trigger x-form-date-trigger"}],
c=this.availableTimeFields.join(""),d=0;d<this.timeFields.length;d++){a=this.timeFields.charAt(d);if(!(c.indexOf(a)<0)){a=this.formatMap[a]||a;b.push({tag:"img",src:Ext.BLANK_IMAGE_URL,cls:"x-form-trigger x-form-time-"+a+"-trigger"})}}this.triggerConfig={tag:"span",cls:"x-form-dateTime-triggers",cn:b}},onResize:function(a,b){Ext.form.TriggerField.superclass.onResize.call(this,a,b);b=this.trigger.getWidth()||17*(this.timeFields.length+1);var c=this.el.getWidth();if(typeof a=="number"){c=a-b;this.el.setWidth(c)}this.wrap.setWidth(c+
b)},getTrigger:function(a){return this.triggers[a]},setMinValue:function(a){this.minValue=typeof a=="string"?this.parseDate(a):a;this.menu&&this.menu.picker.setMinDate(new Date(this.minValue.getTime()))},setMaxValue:function(a){this.maxValue=typeof a=="string"?this.parseDate(a):a;this.menu&&this.menu.picker.setMaxDate(new Date(this.maxValue.getTime()))},onTriggerClick:function(){if(!this.disabled){if(this.menu==null)this.menu=new Ext.menu.DateMenu({hideOnClick:false});Ext.apply(this.menu.picker,{minDate:this.minValue?
new Date(this.minValue.getTime()):this.minValue,maxDate:this.maxValue?new Date(this.maxValue.getTime()):this.maxValue,disabledDatesRE:this.disabledDatesRE,disabledDatesText:this.disabledDatesText,disabledDays:this.disabledDays,disabledDaysText:this.disabledDaysText,format:this.format,showToday:this.showToday,todayIsNow:true,minText:String.format(this.minText,this.formatDate(this.minValue)),maxText:String.format(this.maxText,this.formatDate(this.maxValue))});this.menu.picker.setValue(this.getValue()||
new Date);this.menu.show(this.el,"tl-bl?");this.menuEvents("on")}},onSelect:function(a,b){new Date(b.getTime());if(this.getValue()){b.setHours(this.getValue().getHours());b.setSeconds(this.getValue().getSeconds());b.setMinutes(this.getValue().getMinutes())}this.setValue(b);this.fireEvent("select",this,b);this.menu.hide()},initTrigger:function(){var a=this.trigger.select(".x-form-trigger",true);this.wrap.setStyle("overflow","hidden");this.timeFieldHandlers=[];var b=this;a.each(function(c,d,e){c.hide=
function(){var f=b.wrap.getWidth();this.dom.style.display="none";b.el.setWidth(f-b.trigger.getWidth())};c.show=function(){var f=b.wrap.getWidth();this.dom.style.display="";b.el.setWidth(f-b.trigger.getWidth())};if(e>0){d=b.timeFields.charAt(e-1);d=this.formatMap[d]||d;d=new Cls.form.TimeFieldHandler({parent:this,timeField:d});c.on("click",d.onTriggerClick,d,{preventDefault:true});b.timeFieldHandlers.push(d)}else c.on("click",this.onTriggerClick,this,{preventDefault:true});c.addClassOnOver("x-form-trigger-over");
c.addClassOnClick("x-form-trigger-click")},this);this.triggers=a.elements},onDestroy:function(){if(this.timeFieldHandlers){for(var a=this.timeFieldHandlers.length-1;a>=0;a--){var b=this.timeFieldHandlers[a];b.destroy();this.timeFieldHandlers[a]=null;delete b}this.timeFieldHandlers=null}Cls.form.DateTimeField.superclass.onDestroy.call(this)},validateBlur:function(){if(!Cls.form.DateTimeField.superclass.validateBlur.call(this))return false;for(var a=this.timeFieldHandlers.length-1;a>=0;a--)if(!this.timeFieldHandlers[a].validateBlur())return false;
return true}});Ext.reg("datetimefield",Cls.form.DateTimeField);Cls.form.TimeFieldHandler=function(a){Ext.apply(this,a)};
Ext.extend(Cls.form.TimeFieldHandler,Ext.util.Observable,{parent:null,timeField:null,menu:null,onTriggerClick:function(){if(!this.parent.disabled){if(this.menu==null)this.menu=new Cls.menu.TimeFieldMenu({timeField:this.timeField});Ext.apply(this.menu.picker,{minDate:this.parent.minValue,maxDate:this.parent.maxValue,minText:String.format(this.parent.minText,this.parent.formatDate(this.parent.minValue)),maxText:String.format(this.parent.maxText,this.parent.formatDate(this.parent.maxValue))});this.menu.picker.setValue(this.parent.getValue()||
new Date);this.menu.show(this.parent.el,"tl-bl?");this.menuEvents("on")}},menuEvents:function(a){this.menu[a]("select",this.onSelect,this);this.menu[a]("hide",this.onMenuHide,this);this.menu[a]("show",this.parent.onFocus,this)},onSelect:function(a,b){if(this.parent.getValue()){a=new Date(this.parent.getValue().getTime());this.menu.picker.copyTimeField(b,a);this.parent.setValue(a)}else this.parent.setValue(b);this.parent.fireEvent("select",this,b);this.menu.hide()},onMenuHide:function(){this.parent.focus(false,
60);this.menuEvents("un")},destroy:function(){this.menu&&this.menu.destroy()},validateBlur:function(){return!this.menu||!this.menu.isVisible()}});
Cls.menu.TimeFieldMenu=Ext.extend(Ext.menu.Menu,{cls:"x-timeField-menu",enableScrolling:false,initComponent:function(){this.on("beforeshow",this.onBeforeShow,this);if(this.strict=Ext.isIE7&&Ext.isStrict)this.on("show",this.onShow,this,{single:true,delay:20});var a=Ext.apply({internalRender:this.strict||!Ext.isIE,ctCls:"x-menu-timeField-item"},this.initialConfig);Ext.apply(this,{plain:true,items:this.picker=Ext.ComponentMgr.create(a,"timepicker"+this.initialConfig.timeField)});this.picker.purgeListeners();
Cls.menu.TimeFieldMenu.superclass.initComponent.call(this);me=this;this.relayEvents(this.picker,["select"])},onBeforeShow:function(){},onClick:function(){this.hideOnClick&&this.hide(true)},onShow:function(){var a=this.picker.getEl();a.setWidth(a.getWidth())},beforeDestroy:function(){this.picker.destroy()}});
Cls.TimeFieldPicker=Ext.extend(Ext.Component,{minText:"This date is before the minimum date",maxText:"This date is after the maximum date",nowText:"Now",constrainToViewport:true,initComponent:function(){Cls.TimeFieldPicker.superclass.initComponent.call(this);var a=this.value;this.value=new Date;a&&this.value.setTime(a.getTime());this.addEvents("select");if(this.handler)this.on("select",this.handler,this.scope||this)},setMinDate:function(a){this.minDate=a;this.update(this.value,true)},setMaxDate:function(a){this.maxDate=
a;this.update(this.value,true)},setValue:function(a){this.value=new Date;this.value.setTime(a.getTime());this.el&&this.update(this.value,true)},getValue:function(){return this.value},focus:function(){this.el&&this.update(this.activeDate)},onRender:function(a,b){var c=['<table cellspacing="0" width="'+this.columns*25+'">','<tr><td class="x-date-middle" align="center">'+this.header+"</td></tr>",'<tr><td><table class="x-date-inner" cellspacing="0">'];c[c.length]="<tbody><tr>";for(var d=0;d<this.max;d++){if(d%
this.columns==0&&d!=0)c[c.length]="</tr><tr>";c[c.length]='<td><a href="#" hidefocus="on" class="x-date-date" tabIndex="1"><em><span>'+(d<10?"0"+d:""+d)+"</span></em></a></td>"}c.push("</tr></tbody></table></td></tr>",'</table><div class="x-date-mp"></div>');c=document.createElement("div");c.className="x-date-picker";c.innerHTML=this.generateContent();a.dom.insertBefore(c,b);this.el=Ext.get(c);this.eventEl=Ext.get(c.firstChild);this.eventEl.on("mousewheel",this.handleMouseWheel,this);new Ext.KeyNav(this.eventEl,
{left:function(){this.update(this.activeDate.add(this.timeField,-1))},right:function(){this.update(this.activeDate.add(this.timeField,1))},up:function(){this.update(this.activeDate.add(this.timeField,-this.columns))},down:function(){this.update(this.activeDate.add(this.timeField,this.columns))},enter:function(e){e.stopPropagation();return true},scope:this});this.eventEl.on("click",this.handleDateClick,this,{delegate:"a.x-date-date"});this.el.unselectable();this.cells=this.el.select("table.x-date-inner tbody td");
Ext.isIE&&this.el.repaint();this.update(this.value)},generateContent:function(){var a=['<table cellspacing="0" width="'+this.columns*25+'">','<tr><td class="x-date-middle" align="center">'+this.header+"</td></tr>",'<tr><td><table class="x-date-inner" cellspacing="0">'];a[a.length]="<tbody><tr>";for(var b=0;b<this.max;b++){if(b%this.columns==0&&b!=0)a[a.length]="</tr><tr>";a[a.length]='<td><a href="#" hidefocus="on" class="x-date-date" tabIndex="1"><em><span>'+(b<10?"0"+b:""+b)+"</span></em></a></td>"}a.push("</tr></tbody></table></td></tr>",
'</table><div class="x-date-mp"></div>');return a.join("")},handleMouseWheel:function(a){var b=a.getWheelDelta();if(b>0){this.update(this.activeDate.add(this.timeField,1));a.stopEvent()}else if(b<0){this.update(this.activeDate.add(this.timeField,-1));a.stopEvent()}},handleDateClick:function(a,b){a.stopEvent();if(b.timeFieldValue!=undefined&&!Ext.fly(b.parentNode).hasClass("x-date-disabled")){a=new Date(this.activeDate.getTime());this.updateTimeField(a,b.timeFieldValue);this.setValue(a);this.fireEvent("select",
this,this.value)}},update:function(a,b){var c=this.activeDate;this.activeDate=a;if(!b&&c&&this.el){var d=this.extractTimeField(a);this.cells.removeClass("x-date-selected");this.cells.each(function(k){if(k.dom.firstChild.timeFieldValue==d){k.addClass("x-date-selected");setTimeout(function(){try{k.dom.firstChild.focus()}catch(j){}},50);return false}})}else{this.cells.removeClass("x-date-selected");b=this.cells.elements;var e=new Date,f=this.minDate?this.minTime(this.minDate).getTime():Number.NEGATIVE_INFINITY,
h=this.maxDate?this.maxTime(this.maxDate).getTime():Number.POSITIVE_INFINITY,i=new Date(a.getTime()),g=this;c=function(k,j){j.title="";var o=i.getTime(),n=g.extractTimeField(i);j.firstChild.timeFieldValue=n;if(n==g.extractTimeField(e)){j.className+=" x-date-today";j.title=k.nowText}if(n==g.extractTimeField(a)){j.className+=" x-date-selected";setTimeout(function(){try{j.firstChild.focus()}catch(r){}},50)}if(o<f){j.className=" x-date-disabled";j.title=k.minText}else if(o>h){j.className=" x-date-disabled";
j.title=k.maxText}};for(var l=0;l<this.max;l++){this.updateTimeField(i,l);b[l].className="x-date-active";c(this,b[l])}if(!this.internalRender){b=this.el.dom.firstChild;c=b.offsetWidth;this.el.setWidth(c+this.el.getBorderWidth("lr"));Ext.fly(b).setWidth(c);this.internalRender=true;if(Ext.isOpera&&!this.secondPass){b.rows[0].cells[1].style.width=c-(b.rows[0].cells[0].offsetWidth+b.rows[0].cells[2].offsetWidth)+"px";this.secondPass=true;this.update.defer(10,this,[a])}}}},updateTimeField:Ext.emptyFn,
extractTimeField:Ext.emptyFn,copyTimeField:function(a,b){this.updateTimeField(b,this.extractTimeField(a))},minTime:function(a){return new Date(Math.floor(a.getTime()/this.fieldInMillis)*this.fieldInMillis)},maxTime:function(a){return new Date((Math.floor(a.getTime()/this.fieldInMillis)+1)*this.fieldInMillis-1)}});Cls.DateHourPicker=Ext.extend(Cls.TimeFieldPicker,{max:24,columns:6,timeField:"H",header:"Hours",fieldInMillis:36E5,updateTimeField:function(a,b){a.setHours(b)},extractTimeField:function(a){return a.getHours()}});
Ext.reg("timepickerH",Cls.DateHourPicker);
Cls.DateAMPMHourPicker=Ext.extend(Cls.DateHourPicker,{timeField:"h",generateContent:function(){var a=['<table cellspacing="0" width="'+this.columns*25+'">','<tr><td class="x-date-middle" align="center">'+this.header+"</td></tr>"];a.push(this.generateXMContent("AM"));a.push(this.generateXMContent("PM"));a.push('</table><div class="x-date-mp"></div>');return a.join("")},generateXMContent:function(a){a=["<tr><td>",'<table class="x-date-inner" cellspacing="0">','<th colspan="6"><span>'+a+"</span></th>",
"<tbody><tr>"];for(var b=0;b<12;b++){if(b%this.columns==0&&b!=0)a[a.length]="</tr><tr>";a[a.length]='<td><a href="#" hidefocus="on" class="x-date-date" tabIndex="1"><em><span>'+(b<10?"0"+b:""+b)+"</span></em></a></td>"}a.push("</tr></tbody></table></td></tr>");return a.join("")}});Ext.reg("timepickerh",Cls.DateAMPMHourPicker);Cls.DateMinutePicker=Ext.extend(Cls.TimeFieldPicker,{max:60,columns:10,timeField:"i",header:"Minutes",fieldInMillis:6E4,updateTimeField:function(a,b){a.setMinutes(b)},extractTimeField:function(a){return a.getMinutes()}});
Ext.reg("timepickeri",Cls.DateMinutePicker);Cls.DateSecondPicker=Ext.extend(Cls.DateMinutePicker,{timeField:"s",header:"Seconds",fieldInMillis:1E3,updateTimeField:function(a,b){a.setSeconds(b)},extractTimeField:function(a){return a.getSeconds()}});Ext.reg("timepickers",Cls.DateSecondPicker);Ext.ux.GDataTableAdapter=function(){return{adapt:function(a){for(var b=new google.visualization.DataTable,c=a.columns,d=0;d<c.length;d++){var e=c[d];b.addColumn("string",e.label||e,e.dataIndex||e)}a=a.datas;b.addRows(a.length);for(d=0;d<a.length;d++)for(e=0;e<c.length;e++)if(e==0){b.setValue(d,e,a[d][c[e]].v);b.setFormattedValue(d,e,a[d][c[e]].f)}else b.setValue(d,e,a[d][c[e]]);return b}}}();
Ext.ux.GVisualizationPanel=Ext.extend(Ext.Panel,{autoScroll:true,visualizationAPI:"visualization",visualizationAPIVer:"1",visualizationPkgs:{intensitymap:"IntensityMap",orgchart:"OrgChart",linechart:"LineChart",gauge:"Gauge",scatterchart:"ScatterChart"},directFn:undefined,visualizationPkg:"",html:"Loading...",store:null,initComponent:function(){if(typeof this.visualizationPkg==="object"){Ext.apply(this.visualizationPkgs,this.visualizationPkg);for(var a in this.visualizationPkg){this.visualizationPkg=
a;break}}google.load(this.visualizationAPI,this.visualizationAPIVer,{packages:[this.visualizationPkg],callback:this.onLoadCallback.createDelegate(this)});Ext.ux.GVisualizationPanel.superclass.initComponent.call(this)},onLoadCallback:function(){this.directFn(function(a){var b={datas:[],columns:this.columns};if(a&&a.results)b={datas:a.results,columns:this.columns};this.datatable=Ext.ux.GDataTableAdapter.adapt(b);a=this.visualizationPkgs[this.visualizationPkg];this.body.update("");this.visualization=
new google.visualization[a](this.body.dom);google.visualization.events.addListener(this.visualization,"select",function(){this.fireEvent("select",this,this.visualization)}.createDelegate(this));this.visualization.draw(this.datatable,Ext.apply({},this.visualizationCfg))},this)}});Ext.reg("gvisualization",Ext.ux.GVisualizationPanel);